ci:
  skip:
    - pylint
    - deptry
    - doctest-package
    - doctest-readme
    - docsig
    - vulture
    - tests
    - copyright-year
    - doctest-examples
    - make-docs
    - update-readme
    - update-docs
    - update-whitelist
default_language_version:
  python: "3.9"
default_stages:
  - commit
exclude: |
  (?x)^(
    | poetry\.lock
    | migrations\/.*
    | \.bumpversion\.cfg
    | whitelist\.py
    | \.idea\/.*
    | tests\/TESTS\.md
    | docs\/conf\.py
  )$
repos:
  - repo: local
    hooks:
      # local so package can be imported to lint
      - id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        types:
          - python
        exclude: ^(docs/conf\.py)$
      # no hooks found for `doctest`
      - id: doctest-package
        name: doctest docstrings
        language: system
        entry: poetry run make doctest-package
        pass_filenames: false
      # no hooks found for `doctest`
      - id: doctest-readme
        name: doctest readme
        language: system
        entry: poetry run make doctest-readme
        pass_filenames: false
      # infer imports for overridden methods
      - id: docsig
        name: check signature documentation
        language: system
        entry: poetry run make params
        pass_filenames: false
      # analyze all files for reliable result
      - id: vulture
        name: check for unused code
        language: system
        entry: poetry run make unused
        pass_filenames: false
      # script also handles coverage
      - id: tests
        name: test source code
        language: system
        entry: poetry run make tests
        pass_filenames: false
      # check imports against dependencies
      - id: deptry
        name: deptry
        description: |
          deptry is a command line tool to check for issues with dependencies
          in a Python project, such as obsolete or missing dependencies.
        entry: poetry run deptry .
        language: system
        always_run: true
        pass_filenames: false
      # check copyright year in license
      - id: copyright-year
        name: copyright year
        language: system
        entry: poetry run make update-copyright
        pass_filenames: false
      - id: doctest-examples
        name: doctest examples
        language: system
        entry: poetry run make doctest-docs
        pass_filenames: false
      - id: make-docs
        name: make docs
        language: system
        entry: poetry run make docs
        pass_filenames: false
      - id: update-readme
        name: update readme
        language: system
        entry: poetry run make update-readme
        pass_filenames: false
      - id: update-docs
        name: update docs
        language: system
        entry: poetry run make update-docs
        pass_filenames: false
      - id: update-whitelist
        name: update whitelist
        language: system
        entry: poetry run make whitelist
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.6.0"
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
        exclude: ^(.*\.rst)$
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
        exclude: ^(.*test\.key)$
      - id: forbid-submodules
      - id: no-commit-to-branch
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: pretty-format-json
        args:
          - "--autofix"
      - id: fix-encoding-pragma
        args:
          - "--remove"
  - repo: https://github.com/ikamensh/flynt
    rev: "1.0.1"
    hooks:
      - id: flynt
        args:
          - "--line-length=79"
          - "--transform-concats"
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        args:
          - "--write"
        exclude: ^(CHANGELOG\.md|.*\.json|SECURITY\.md)$
  - repo: https://github.com/PyCQA/docformatter
    rev: "v1.7.5"
    hooks:
      - id: docformatter
        args:
          - "--recursive"
          - "--wrap-summaries=72"
          - "--in-place"
  - repo: https://github.com/pappasam/toml-sort
    rev: "v0.23.1"
    hooks:
      - id: toml-sort
        args:
          - "--in-place"
          - "--all"
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: "v1.10.0"
    hooks:
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
  - repo: https://github.com/pre-commit/pre-commit
    rev: "v3.7.1"
    hooks:
      - id: validate_manifest
  - repo: https://github.com/siderolabs/conform
    rev: "v0.1.0-alpha.30"
    hooks:
      - id: conform
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.8"
    hooks:
      - id: bandit
        args:
          - "--recursive"
          - "-lll"
  - repo: https://github.com/asottile/pyupgrade
    rev: "v3.15.2"
    hooks:
      - id: pyupgrade
        args:
          - "--py38-plus"
  - repo: https://github.com/PyCQA/flake8
    rev: "7.0.0"
    hooks:
      - id: flake8
        exclude: ^(.*\/)?(_?templates\.py|exclude_test\.py)
        additional_dependencies:
          - flake8-bugbear==22.12.6
  - repo: https://github.com/adrienverge/yamllint.git
    rev: "v1.35.1"
    hooks:
      - id: yamllint
        args:
          - "--config-data={rules: {line-length: {max: 79}}}"
  - repo: https://github.com/psf/black
    rev: "24.4.2"
    hooks:
      - id: black
        additional_dependencies:
          - tomli==2.0.1
  - repo: https://github.com/pycqa/isort
    rev: "5.13.2"
    hooks:
      - id: isort
  - repo: https://github.com/codespell-project/codespell
    rev: "v2.2.6"
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
  - repo: https://github.com/tox-dev/tox-ini-fmt
    rev: "1.3.1"
    hooks:
      - id: tox-ini-fmt
  - repo: https://github.com/dannysepler/rm_unneeded_f_str
    rev: "v0.2.0"
    hooks:
      - id: rm-unneeded-f-str
  - repo: https://github.com/rhysd/actionlint
    rev: "v1.7.0"
    hooks:
      - id: actionlint
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: "2.7.3"
    hooks:
      - id: editorconfig-checker
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.10.0"
    hooks:
      - id: mypy
        additional_dependencies: [types-pyyaml==6.0.12]
