[tox]
requires =
    tox>=4.15
env_list =
    py{314, 313, 312, 311, 310}

[testenv]
commands =
    bash scripts/tox.sh {toxinidir} {work_dir}/{env_name}/docsig
allowlist_externals =
    bash
env_dir = {work_dir}/{env_name}/.tox-venv
env_tmp_dir = {work_dir}/{env_name}/.tox-tmp
