off_by_default  # unused variable (docsig/plugin/_flake8.py:39)
version  # unused variable (docsig/plugin/_flake8.py:41)
_.add_options  # unused method (docsig/plugin/_flake8.py:52)
_.parse_options  # unused method (docsig/plugin/_flake8.py:134)
_.run  # unused method (docsig/plugin/_flake8.py:145)
__call__  # unused function (tests/__init__.py:24)
content  # unused variable (tests/__init__.py:24)
__call__  # unused function (tests/__init__.py:31)
