_.excepthook  # unused attribute (docsig/_main.py:25)
off_by_default  # unused variable (docsig/plugin/_flake8.py:81)
version  # unused variable (docsig/plugin/_flake8.py:83)
_.add_options  # unused method (docsig/plugin/_flake8.py:94)
_.parse_options  # unused method (docsig/plugin/_flake8.py:108)
__call__  # unused function (tests/__init__.py:24)
content  # unused variable (tests/__init__.py:24)
__call__  # unused function (tests/__init__.py:31)
