"""
tests
=====

Test package for ``docsig``.
"""

# pylint: disable=too-many-lines
import typing as t
from pathlib import Path

from . import _templates  # noqa

MockMainType = t.Callable[..., t.Union[str, int]]
FixtureFlake8 = t.Callable[..., int]
FixtureMakeTree = t.Callable[[Path, t.Dict[t.Any, t.Any]], None]
FixturePatchArgv = t.Callable[..., None]


class InitFileFixtureType(
    t.Protocol,
):  # pylint: disable=too-few-public-methods
    """Type for ``fixture_init_file``."""

    def __call__(self, content: str, path: Path = ..., /) -> Path:
        """Type for ``fixture_init_file``."""


TEMPLATE = "template"
EXPECTED = "expected"
E10 = "e-1-0"
FAIL = "f"
PASS = "p"
TOML = "pyproject.toml"
TOOL = "tool"
LIST = "list"
CHECK_ARGS = (
    "--check-class",
    "--check-protected",
    "--check-overridden",
    "--check-dunders",
    "--check-property-returns",
    "--check-protected-class-methods",
    "--check-nested",
)
FAIL_CHECK_ARGS = tuple(f"f-{i[8:]}" for i in CHECK_ARGS)
WILL_ERROR = """
#!/bin/bash
echo "Hello World!"
"""
TREE = {
    "file1.txt": [],
    "file2.txt": [],
    "file3.txt": [],
    "file4.txt": [],
    "file5.txt": [],
    "file10.txt": [],
    "file[1].txt": [],
    ".pyaud_cache": {
        "7.5.1": {
            "CACHEDIR.TAG": [WILL_ERROR],
            "files.json": [WILL_ERROR],
            ".gitignore": ["# Created by pyaud automatically.", "*"],
        },
    },
    "CODE_OF_CONDUCT.md": [WILL_ERROR],
    ".pylintrc": [WILL_ERROR],
    "LICENSE": [WILL_ERROR],
    ".pytest_cache": {
        "CACHEDIR.TAG": [WILL_ERROR],
        "README.md": [WILL_ERROR],
        ".gitignore": ["# Created by pytest automatically.", "*"],
        "v": {
            "cache": {
                "nodeids": [WILL_ERROR],
                "lastfailed": [WILL_ERROR],
                "stepwise": "",
            },
            "randomly_seed": [WILL_ERROR],
        },
    },
    "CHANGELOG.md": [WILL_ERROR],
    "dist": {
        "docsig-0.49.1.tar.gz": [WILL_ERROR],
        "docsig-0.49.2-py3-none-any.whl": [WILL_ERROR],
        "docsig-0.49.2.tar.gz": [WILL_ERROR],
        "docsig-0.49.0-py3-none-any.whl": [WILL_ERROR],
        "docsig-0.49.0.tar.gz": [WILL_ERROR],
        "docsig-0.49.1-py3-none-any.whl": [WILL_ERROR],
    },
    ".pre-commit-config.yaml": [WILL_ERROR],
    ".coverage": [WILL_ERROR],
    "Makefile": [WILL_ERROR],
    "whitelist.py": [],
    ".pre-commit-hooks.yaml": [WILL_ERROR],
    "pyproject.toml": [],
    ".bumpversion.cfg": [WILL_ERROR],
    "node_modules": {
        ".cache": {
            "prettier": {
                ".prettier-caches": {
                    "7f51ae3462154079bc96a79583b977616b1ad315.json": [
                        WILL_ERROR,
                    ],
                },
            },
        },
    },
    "tests": {
        "misc_test.py": [],
        "conftest.py": [],
        "disable_test.py": [],
        "__init__.py": [],
        "__pycache__": {
            "_test.cpython-38-pytest-8.1.1.pyc": [WILL_ERROR],
            "__init__.cpython-38.pyc": [WILL_ERROR],
            "disable_test.cpython-38-pytest-8.1.1.pyc": [WILL_ERROR],
            "misc_test.cpython-38-pytest-8.1.1.pyc": [WILL_ERROR],
            "_test.cpython-38.pyc": [WILL_ERROR],
            "conftest.cpython-38-pytest-8.1.1.pyc": [WILL_ERROR],
        },
        "TESTS.md": [WILL_ERROR],
        "git_test.py": [],
        "_test.py": [],
    },
    ".conform.yaml": [WILL_ERROR],
    "docs": {
        "index.rst": [WILL_ERROR],
        "requirements.txt": [WILL_ERROR],
        "docsig.rst": [WILL_ERROR],
        "conf.py": [],
        "static": {"docsig.svg": [WILL_ERROR]},
        "examples": {
            "classes.rst": [WILL_ERROR],
            "message-control.rst": [WILL_ERROR],
        },
    },
    ".readthedocs.yml": [WILL_ERROR],
    ".prettierignore": [WILL_ERROR],
    ".editorconfig": [WILL_ERROR],
    "docsig": {
        "_stub.py": [],
        "_report.py": [],
        "_main.py": [],
        "_version.py": [],
        "_module.py": [],
        "__init__.py": [],
        "_display.py": [],
        "_hooks.py": [],
        "__pycache__": {
            "_core.cpython-311.pyc": [WILL_ERROR],
            "__init__.cpython-38.pyc": [WILL_ERROR],
            "_core.cpython-38.pyc": [WILL_ERROR],
            "_main.cpython-311.pyc": [WILL_ERROR],
            "_decorators.cpython-38.pyc": [WILL_ERROR],
            "_message.cpython-311.pyc": [WILL_ERROR],
            "_config.cpython-311.pyc": [WILL_ERROR],
            "_config.cpython-38.pyc": [WILL_ERROR],
            "messages.cpython-311.pyc": [WILL_ERROR],
            "_display.cpython-311.pyc": [WILL_ERROR],
            "_display.cpython-38.pyc": [WILL_ERROR],
            "_stub.cpython-311.pyc": [WILL_ERROR],
            "_decorators.cpython-311.pyc": [WILL_ERROR],
            "_hooks.cpython-38.pyc": [WILL_ERROR],
            "_utils.cpython-38.pyc": [WILL_ERROR],
            "_report.cpython-311.pyc": [WILL_ERROR],
            "_directives.cpython-38.pyc": [WILL_ERROR],
            "_hooks.cpython-311.pyc": [WILL_ERROR],
            "__main__.cpython-38.pyc": [WILL_ERROR],
            "_version.cpython-311.pyc": [WILL_ERROR],
            "_utils.cpython-311.pyc": [WILL_ERROR],
            "_module.cpython-311.pyc": [WILL_ERROR],
            "_stub.cpython-38.pyc": [WILL_ERROR],
            "messages.cpython-38.pyc": [WILL_ERROR],
            "_message.cpython-38.pyc": [WILL_ERROR],
            "_report.cpython-38.pyc": [WILL_ERROR],
            "_version.cpython-38.pyc": [WILL_ERROR],
            "_directives.cpython-311.pyc": [WILL_ERROR],
            "_git.cpython-38.pyc": [WILL_ERROR],
            "_module.cpython-38.pyc": [WILL_ERROR],
            "_main.cpython-38.pyc": [WILL_ERROR],
            "__init__.cpython-311.pyc": [WILL_ERROR],
            "__main__.cpython-311.pyc": [WILL_ERROR],
        },
        "_message.py": [],
        "_core.py": [],
        "_decorators.py": [],
        "messages.py": [],
        "py.typed": [WILL_ERROR],
        "_config.py": [],
        "__main__.py": [],
        "_utils.py": [],
        "_directives.py": [],
    },
    ".mypy_cache": {
        "CACHEDIR.TAG": [WILL_ERROR],
        "3.12": {
            "builtins.meta.json": [WILL_ERROR],
            "genericpath.meta.json": [WILL_ERROR],
            "enum.meta.json": [WILL_ERROR],
            "abc.meta.json": [WILL_ERROR],
            "subprocess.meta.json": [WILL_ERROR],
            "dataclasses.data.json": [WILL_ERROR],
            "typing.data.json": [WILL_ERROR],
            "resource.data.json": [WILL_ERROR],
            "_codecs.meta.json": [WILL_ERROR],
            "posixpath.data.json": [WILL_ERROR],
            "contextlib.meta.json": [WILL_ERROR],
            "_codecs.data.json": [WILL_ERROR],
            "posixpath.meta.json": [WILL_ERROR],
            "contextlib.data.json": [WILL_ERROR],
            "resource.meta.json": [WILL_ERROR],
            "typing.meta.json": [WILL_ERROR],
            "_typeshed": {
                "__init__.meta.json": [WILL_ERROR],
                "__init__.data.json": [WILL_ERROR],
            },
            "abc.data.json": [WILL_ERROR],
            "subprocess.data.json": [WILL_ERROR],
            "zipfile": {
                "_path.data.json": [WILL_ERROR],
                "_path.meta.json": [WILL_ERROR],
                "__init__.meta.json": [WILL_ERROR],
                "__init__.data.json": [WILL_ERROR],
            },
            "dataclasses.meta.json": [WILL_ERROR],
            "genericpath.data.json": [WILL_ERROR],
            "enum.data.json": [WILL_ERROR],
            "builtins.data.json": [WILL_ERROR],
            "@plugins_snapshot.json": [WILL_ERROR],
            "sre_compile.meta.json": [WILL_ERROR],
            "io.data.json": [WILL_ERROR],
            "codecs.data.json": [WILL_ERROR],
            "pathlib.data.json": [WILL_ERROR],
            "typing_extensions.meta.json": [WILL_ERROR],
            "conf.meta.json": [WILL_ERROR],
            "_ast.meta.json": [WILL_ERROR],
            "sre_parse.meta.json": [WILL_ERROR],
            "sys": {
                "__init__.meta.json": [WILL_ERROR],
                "_monitoring.data.json": [WILL_ERROR],
                "_monitoring.meta.json": [WILL_ERROR],
                "__init__.data.json": [WILL_ERROR],
            },
            "_collections_abc.meta.json": [WILL_ERROR],
            "sre_constants.meta.json": [WILL_ERROR],
            "types.data.json": [WILL_ERROR],
            "re.meta.json": [WILL_ERROR],
            "os": {
                "path.data.json": [WILL_ERROR],
                "path.meta.json": [WILL_ERROR],
                "__init__.meta.json": [WILL_ERROR],
                "__init__.data.json": [WILL_ERROR],
            },
            "re.data.json": [WILL_ERROR],
            "types.meta.json": [WILL_ERROR],
            "importlib": {
                "abc.meta.json": [WILL_ERROR],
                "machinery.data.json": [WILL_ERROR],
                "_abc.data.json": [WILL_ERROR],
                "_abc.meta.json": [WILL_ERROR],
                "resources": {
                    "abc.meta.json": [WILL_ERROR],
                    "abc.data.json": [WILL_ERROR],
                    "__init__.meta.json": [WILL_ERROR],
                    "__init__.data.json": [WILL_ERROR],
                },
                "abc.data.json": [WILL_ERROR],
                "machinery.meta.json": [WILL_ERROR],
                "__init__.meta.json": [WILL_ERROR],
                "readers.meta.json": [WILL_ERROR],
                "readers.data.json": [WILL_ERROR],
                "__init__.data.json": [WILL_ERROR],
                "metadata": {
                    "__init__.meta.json": [WILL_ERROR],
                    "_meta.meta.json": [WILL_ERROR],
                    "_meta.data.json": [WILL_ERROR],
                    "__init__.data.json": [WILL_ERROR],
                },
            },
            "sre_constants.data.json": [WILL_ERROR],
            "collections": {
                "abc.meta.json": [WILL_ERROR],
                "abc.data.json": [WILL_ERROR],
                "__init__.meta.json": [WILL_ERROR],
                "__init__.data.json": [WILL_ERROR],
            },
            "_ast.data.json": [WILL_ERROR],
            "_collections_abc.data.json": [WILL_ERROR],
            "sre_parse.data.json": [WILL_ERROR],
            "email": {
                "header.meta.json": [WILL_ERROR],
                "charset.meta.json": [WILL_ERROR],
                "_policybase.meta.json": [WILL_ERROR],
                "message.data.json": [WILL_ERROR],
                "message.meta.json": [WILL_ERROR],
                "charset.data.json": [WILL_ERROR],
                "_policybase.data.json": [WILL_ERROR],
                "header.data.json": [WILL_ERROR],
                "errors.data.json": [WILL_ERROR],
                "__init__.meta.json": [WILL_ERROR],
                "policy.data.json": [WILL_ERROR],
                "contentmanager.data.json": [WILL_ERROR],
                "contentmanager.meta.json": [WILL_ERROR],
                "policy.meta.json": [WILL_ERROR],
                "__init__.data.json": [WILL_ERROR],
                "errors.meta.json": [WILL_ERROR],
            },
            "conf.data.json": [WILL_ERROR],
            "sre_compile.data.json": [WILL_ERROR],
            "io.meta.json": [WILL_ERROR],
            "codecs.meta.json": [WILL_ERROR],
            "typing_extensions.data.json": [WILL_ERROR],
            "pathlib.meta.json": [WILL_ERROR],
        },
        ".gitignore": ["# Automatically created by mypy", "*"],
        "3.8": {
            "atexit.meta.json": [WILL_ERROR],
            "datetime.data.json": [WILL_ERROR],
            "socket.meta.json": [WILL_ERROR],
            "ssl.data.json": [WILL_ERROR],
            "configparser.data.json": [WILL_ERROR],
            "packaging": {
                "tags.data.json": [WILL_ERROR],
                "_manylinux.data.json": [WILL_ERROR],
                "_elffile.data.json": [WILL_ERROR],
                "_structures.meta.json": [WILL_ERROR],
                "markers.data.json": [WILL_ERROR],
                "version.data.json": [WILL_ERROR],
                "_structures.data.json": [WILL_ERROR],
                "markers.meta.json": [WILL_ERROR],
                "version.meta.json": [WILL_ERROR],
                "_elffile.meta.json": [WILL_ERROR],
                "_manylinux.meta.json": [WILL_ERROR],
                "tags.meta.json": [WILL_ERROR],
                "_parser.meta.json": [WILL_ERROR],
                "specifiers.data.json": [WILL_ERROR],
                "utils.meta.json": [WILL_ERROR],
                "__init__.meta.json": [WILL_ERROR],
                "_tokenizer.data.json": [WILL_ERROR],
                "requirements.meta.json": [WILL_ERROR],
                "_musllinux.meta.json": [WILL_ERROR],
                "_musllinux.data.json": [WILL_ERROR],
                "requirements.data.json": [WILL_ERROR],
                "utils.data.json": [WILL_ERROR],
                "__init__.data.json": [WILL_ERROR],
                "_tokenizer.meta.json": [WILL_ERROR],
                "_parser.data.json": [WILL_ERROR],
                "specifiers.meta.json": [WILL_ERROR],
            },
            "platform.meta.json": [WILL_ERROR],
            "difflib.meta.json": [WILL_ERROR],
            "builtins.meta.json": [WILL_ERROR],
            "zlib.meta.json": [WILL_ERROR],
            "ctypes": {
                "__init__.meta.json": [WILL_ERROR],
                "__init__.data.json": [WILL_ERROR],
            },
            "contextvars.data.json": [WILL_ERROR],
            "time.data.json": [WILL_ERROR],
            "token.meta.json": [WILL_ERROR],
            "decimal.data.json": [WILL_ERROR],
            "markupsafe": {
                "_speedups.data.json": [WILL_ERROR],
                "_speedups.meta.json": [WILL_ERROR],
                "_native.meta.json": [WILL_ERROR],
                "__init__.meta.json": [WILL_ERROR],
                "__init__.data.json": [WILL_ERROR],
                "_native.data.json": [WILL_ERROR],
            },
            "unittest": {
                "suite.data.json": [WILL_ERROR],
                "async_case.data.json": [WILL_ERROR],
                "loader.meta.json": [WILL_ERROR],
                "main.data.json": [WILL_ERROR],
                "case.data.json": [WILL_ERROR],
                "case.meta.json": [WILL_ERROR],
                "main.meta.json": [WILL_ERROR],
                "loader.data.json": [WILL_ERROR],
                "async_case.meta.json": [WILL_ERROR],
                "suite.meta.json": [WILL_ERROR],
                "result.data.json": [WILL_ERROR],
                "__init__.meta.json": [WILL_ERROR],
                "runner.data.json": [WILL_ERROR],
                "signals.meta.json": [WILL_ERROR],
                "signals.data.json": [WILL_ERROR],
                "runner.meta.json": [WILL_ERROR],
                "__init__.data.json": [WILL_ERROR],
                "result.meta.json": [WILL_ERROR],
            },
            "opcode.meta.json": [WILL_ERROR],
            "genericpath.meta.json": [WILL_ERROR],
            "_weakrefset.data.json": [WILL_ERROR],
            "shlex.meta.json": [WILL_ERROR],
            "hashlib.meta.json": [WILL_ERROR],
            "tarfile.data.json": [WILL_ERROR],
            "fractions.data.json": [WILL_ERROR],
            "textwrap.data.json": [WILL_ERROR],
            "enum.meta.json": [WILL_ERROR],
            "_ctypes.meta.json": [WILL_ERROR],
            "abc.meta.json": [WILL_ERROR],
            "traceback.meta.json": [WILL_ERROR],
            "random.data.json": [WILL_ERROR],
            "subprocess.meta.json": [WILL_ERROR],
            "itertools.meta.json": [WILL_ERROR],
            "dataclasses.data.json": [WILL_ERROR],
            "typing.data.json": [WILL_ERROR],
            "_heapq.data.json": [WILL_ERROR],
            "gc.data.json": [WILL_ERROR],
            "_decimal.data.json": [WILL_ERROR],
            "base64.meta.json": [WILL_ERROR],
            "pdb.data.json": [WILL_ERROR],
            "queue.meta.json": [WILL_ERROR],
            "_bisect.meta.json": [WILL_ERROR],
            "_locale.meta.json": [WILL_ERROR],
            "dis.meta.json": [WILL_ERROR],
            "object_colors": {
                "_version.data.json": [WILL_ERROR],
                "_version.meta.json": [WILL_ERROR],
                "__init__.meta.json": [WILL_ERROR],
                "__init__.data.json": [WILL_ERROR],
            },
            "pytest": {
                "__init__.meta.json": [WILL_ERROR],
                "__init__.data.json": [WILL_ERROR],
            },
            "_codecs.meta.json": [WILL_ERROR],
            "glob.meta.json": [WILL_ERROR],
            "posixpath.data.json": [WILL_ERROR],
            "gettext.meta.json": [WILL_ERROR],
            "errno.meta.json": [WILL_ERROR],
            "argparse.data.json": [WILL_ERROR],
            "contextlib.meta.json": [WILL_ERROR],
            "shutil.meta.json": [WILL_ERROR],
            "zipimport.data.json": [WILL_ERROR],
            "termios.data.json": [WILL_ERROR],
            "_codecs.data.json": [WILL_ERROR],
            "jinja2": {
                "compiler.meta.json": [WILL_ERROR],
                "visitor.data.json": [WILL_ERROR],
                "bccache.data.json": [WILL_ERROR],
                "optimizer.meta.json": [WILL_ERROR],
                "loaders.data.json": [WILL_ERROR],
                "async_utils.meta.json": [WILL_ERROR],
                "filters.data.json": [WILL_ERROR],
                "runtime.data.json": [WILL_ERROR],
                "sandbox.meta.json": [WILL_ERROR],
                "parser.data.json": [WILL_ERROR],
                "nodes.meta.json": [WILL_ERROR],
                "tests.meta.json": [WILL_ERROR],
                "tests.data.json": [WILL_ERROR],
                "parser.meta.json": [WILL_ERROR],
                "nodes.data.json": [WILL_ERROR],
                "filters.meta.json": [WILL_ERROR],
                "async_utils.data.json": [WILL_ERROR],
                "runtime.meta.json": [WILL_ERROR],
                "sandbox.data.json": [WILL_ERROR],
                "bccache.meta.json": [WILL_ERROR],
                "optimizer.data.json": [WILL_ERROR],
                "loaders.meta.json": [WILL_ERROR],
                "compiler.data.json": [WILL_ERROR],
                "visitor.meta.json": [WILL_ERROR],
                "defaults.meta.json": [WILL_ERROR],
                "utils.meta.json": [WILL_ERROR],
                "__init__.meta.json": [WILL_ERROR],
                "exceptions.meta.json": [WILL_ERROR],
                "lexer.meta.json": [WILL_ERROR],
                "idtracking.meta.json": [WILL_ERROR],
                "environment.data.json": [WILL_ERROR],
                "ext.meta.json": [WILL_ERROR],
                "_identifier.meta.json": [WILL_ERROR],
                "debug.data.json": [WILL_ERROR],
                "_identifier.data.json": [WILL_ERROR],
                "debug.meta.json": [WILL_ERROR],
                "environment.meta.json": [WILL_ERROR],
                "ext.data.json": [WILL_ERROR],
                "exceptions.data.json": [WILL_ERROR],
                "lexer.data.json": [WILL_ERROR],
                "idtracking.data.json": [WILL_ERROR],
                "utils.data.json": [WILL_ERROR],
                "__init__.data.json": [WILL_ERROR],
                "defaults.data.json": [WILL_ERROR],
            },
            "glob.data.json": [WILL_ERROR],
            "gettext.data.json": [WILL_ERROR],
            "posixpath.meta.json": [WILL_ERROR],
            "contextlib.data.json": [WILL_ERROR],
            "shutil.data.json": [WILL_ERROR],
            "argparse.meta.json": [WILL_ERROR],
            "errno.data.json": [WILL_ERROR],
            "termios.meta.json": [WILL_ERROR],
            "zipimport.meta.json": [WILL_ERROR],
            "_bisect.data.json": [WILL_ERROR],
            "_locale.data.json": [WILL_ERROR],
            "dis.data.json": [WILL_ERROR],
            "multiprocessing": {
                "queues.meta.json": [WILL_ERROR],
                "process.meta.json": [WILL_ERROR],
                "reduction.data.json": [WILL_ERROR],
                "shared_memory.meta.json": [WILL_ERROR],
                "pool.meta.json": [WILL_ERROR],
                "managers.meta.json": [WILL_ERROR],
                "context.data.json": [WILL_ERROR],
                "popen_spawn_posix.data.json": [WILL_ERROR],
                "popen_fork.data.json": [WILL_ERROR],
                "popen_fork.meta.json": [WILL_ERROR],
                "popen_spawn_posix.meta.json": [WILL_ERROR],
                "context.meta.json": [WILL_ERROR],
                "managers.data.json": [WILL_ERROR],
                "pool.data.json": [WILL_ERROR],
                "queues.data.json": [WILL_ERROR],
                "process.data.json": [WILL_ERROR],
                "reduction.meta.json": [WILL_ERROR],
                "shared_memory.data.json": [WILL_ERROR],
                "connection.data.json": [WILL_ERROR],
                "spawn.data.json": [WILL_ERROR],
                "__init__.meta.json": [WILL_ERROR],
                "util.meta.json": [WILL_ERROR],
                "popen_spawn_win32.data.json": [WILL_ERROR],
                "synchronize.data.json": [WILL_ERROR],
                "sharedctypes.meta.json": [WILL_ERROR],
                "popen_forkserver.meta.json": [WILL_ERROR],
                "popen_forkserver.data.json": [WILL_ERROR],
                "popen_spawn_win32.meta.json": [WILL_ERROR],
                "sharedctypes.data.json": [WILL_ERROR],
                "synchronize.meta.json": [WILL_ERROR],
                "util.data.json": [WILL_ERROR],
                "__init__.data.json": [WILL_ERROR],
                "spawn.meta.json": [WILL_ERROR],
                "connection.meta.json": [WILL_ERROR],
            },
            "templatest": {
                "_version.data.json": [WILL_ERROR],
                "_collections.data.json": [WILL_ERROR],
                "_abc.data.json": [WILL_ERROR],
                "_abc.meta.json": [WILL_ERROR],
                "_collections.meta.json": [WILL_ERROR],
                "_version.meta.json": [WILL_ERROR],
                "_objects.meta.json": [WILL_ERROR],
                "templates.meta.json": [WILL_ERROR],
                "utils.meta.json": [WILL_ERROR],
                "__init__.meta.json": [WILL_ERROR],
                "exceptions.meta.json": [WILL_ERROR],
                "exceptions.data.json": [WILL_ERROR],
                "utils.data.json": [WILL_ERROR],
                "__init__.data.json": [WILL_ERROR],
                "templates.data.json": [WILL_ERROR],
                "_objects.data.json": [WILL_ERROR],
            },
            "typing.meta.json": [WILL_ERROR],
            "_heapq.meta.json": [WILL_ERROR],
            "_decimal.meta.json": [WILL_ERROR],
            "gc.meta.json": [WILL_ERROR],
            "_typeshed": {
                "__init__.meta.json": [WILL_ERROR],
                "__init__.data.json": [WILL_ERROR],
            },
            "pathspec": {
                "pathspec.data.json": [WILL_ERROR],
                "pattern.data.json": [WILL_ERROR],
                "gitignore.data.json": [WILL_ERROR],
                "patterns": {
                    "__init__.meta.json": [WILL_ERROR],
                    "gitwildmatch.meta.json": [WILL_ERROR],
                    "gitwildmatch.data.json": [WILL_ERROR],
                    "__init__.data.json": [WILL_ERROR],
                },
                "gitignore.meta.json": [WILL_ERROR],
                "pattern.meta.json": [WILL_ERROR],
                "pathspec.meta.json": [WILL_ERROR],
                "__init__.meta.json": [WILL_ERROR],
                "util.meta.json": [WILL_ERROR],
                "_meta.meta.json": [WILL_ERROR],
                "_meta.data.json": [WILL_ERROR],
                "util.data.json": [WILL_ERROR],
                "__init__.data.json": [WILL_ERROR],
            },
            "pdb.meta.json": [WILL_ERROR],
            "queue.data.json": [WILL_ERROR],
            "base64.data.json": [WILL_ERROR],
            "urllib": {
                "parse.data.json": [WILL_ERROR],
                "__init__.meta.json": [WILL_ERROR],
                "__init__.data.json": [WILL_ERROR],
                "parse.meta.json": [WILL_ERROR],
            },
            "abc.data.json": [WILL_ERROR],
            "itertools.data.json": [WILL_ERROR],
            "subprocess.data.json": [WILL_ERROR],
            "traceback.data.json": [WILL_ERROR],
            "random.meta.json": [WILL_ERROR],
            "dataclasses.meta.json": [WILL_ERROR],
            "tests": {
                "disable_test.meta.json": [WILL_ERROR],
                "disable_test.data.json": [WILL_ERROR],
                "_test.data.json": [WILL_ERROR],
                "conftest.meta.json": [WILL_ERROR],
                "__init__.meta.json": [WILL_ERROR],
                "misc_test.meta.json": [WILL_ERROR],
                "misc_test.data.json": [WILL_ERROR],
                "__init__.data.json": [WILL_ERROR],
                "conftest.data.json": [WILL_ERROR],
                "_test.meta.json": [WILL_ERROR],
            },
            "opcode.data.json": [WILL_ERROR],
            "genericpath.data.json": [WILL_ERROR],
            "decimal.meta.json": [WILL_ERROR],
            "hashlib.data.json": [WILL_ERROR],
            "shlex.data.json": [WILL_ERROR],
            "tarfile.meta.json": [WILL_ERROR],
            "_weakrefset.meta.json": [WILL_ERROR],
            "enum.data.json": [WILL_ERROR],
            "importlib_metadata": {
                "_itertools.data.json": [WILL_ERROR],
                "_adapters.data.json": [WILL_ERROR],
                "_collections.data.json": [WILL_ERROR],
                "compat": {
                    "py39.data.json": [WILL_ERROR],
                    "__init__.meta.json": [WILL_ERROR],
                    "__init__.data.json": [WILL_ERROR],
                    "py39.meta.json": [WILL_ERROR],
                },
                "_text.meta.json": [WILL_ERROR],
                "_text.data.json": [WILL_ERROR],
                "_adapters.meta.json": [WILL_ERROR],
                "_collections.meta.json": [WILL_ERROR],
                "_itertools.meta.json": [WILL_ERROR],
                "__init__.meta.json": [WILL_ERROR],
                "_meta.meta.json": [WILL_ERROR],
                "_compat.data.json": [WILL_ERROR],
                "_functools.meta.json": [WILL_ERROR],
                "_functools.data.json": [WILL_ERROR],
                "_meta.data.json": [WILL_ERROR],
                "_compat.meta.json": [WILL_ERROR],
                "__init__.data.json": [WILL_ERROR],
            },
            "textwrap.meta.json": [WILL_ERROR],
            "fractions.meta.json": [WILL_ERROR],
            "_ctypes.data.json": [WILL_ERROR],
            "click": {
                "core.meta.json": [WILL_ERROR],
                "decorators.meta.json": [WILL_ERROR],
                "formatting.data.json": [WILL_ERROR],
                "parser.data.json": [WILL_ERROR],
                "globals.data.json": [WILL_ERROR],
                "globals.meta.json": [WILL_ERROR],
                "parser.meta.json": [WILL_ERROR],
                "formatting.meta.json": [WILL_ERROR],
                "decorators.data.json": [WILL_ERROR],
                "core.data.json": [WILL_ERROR],
                "termui.meta.json": [WILL_ERROR],
                "utils.meta.json": [WILL_ERROR],
                "__init__.meta.json": [WILL_ERROR],
                "exceptions.meta.json": [WILL_ERROR],
                "_termui_impl.data.json": [WILL_ERROR],
                "shell_completion.data.json": [WILL_ERROR],
                "_compat.data.json": [WILL_ERROR],
                "types.data.json": [WILL_ERROR],
                "_compat.meta.json": [WILL_ERROR],
                "types.meta.json": [WILL_ERROR],
                "shell_completion.meta.json": [WILL_ERROR],
                "exceptions.data.json": [WILL_ERROR],
                "_termui_impl.meta.json": [WILL_ERROR],
                "utils.data.json": [WILL_ERROR],
                "__init__.data.json": [WILL_ERROR],
                "termui.data.json": [WILL_ERROR],
            },
            "zlib.data.json": [WILL_ERROR],
            "builtins.data.json": [WILL_ERROR],
            "contextvars.meta.json": [WILL_ERROR],
            "time.meta.json": [WILL_ERROR],
            "@plugins_snapshot.json": [WILL_ERROR],
            "token.data.json": [WILL_ERROR],
            "html": {
                "__init__.meta.json": [WILL_ERROR],
                "__init__.data.json": [WILL_ERROR],
            },
            "platform.data.json": [WILL_ERROR],
            "difflib.data.json": [WILL_ERROR],
            "datetime.meta.json": [WILL_ERROR],
            "atexit.data.json": [WILL_ERROR],
            "socket.data.json": [WILL_ERROR],
            "ssl.meta.json": [WILL_ERROR],
            "exceptiongroup": {
                "_version.data.json": [WILL_ERROR],
                "_formatting.data.json": [WILL_ERROR],
                "_catch.meta.json": [WILL_ERROR],
                "_suppress.data.json": [WILL_ERROR],
                "_suppress.meta.json": [WILL_ERROR],
                "_catch.data.json": [WILL_ERROR],
                "_version.meta.json": [WILL_ERROR],
                "_formatting.meta.json": [WILL_ERROR],
                "_exceptions.meta.json": [WILL_ERROR],
                "__init__.meta.json": [WILL_ERROR],
                "__init__.data.json": [WILL_ERROR],
                "_exceptions.data.json": [WILL_ERROR],
            },
            "configparser.meta.json": [WILL_ERROR],
            "pprint.meta.json": [WILL_ERROR],
            "sre_compile.meta.json": [WILL_ERROR],
            "selectors.meta.json": [WILL_ERROR],
            "tty.data.json": [WILL_ERROR],
            "io.data.json": [WILL_ERROR],
            "codecs.data.json": [WILL_ERROR],
            "warnings.meta.json": [WILL_ERROR],
            "pathlib.data.json": [WILL_ERROR],
            "typing_extensions.meta.json": [WILL_ERROR],
            "_warnings.meta.json": [WILL_ERROR],
            "tokenize.data.json": [WILL_ERROR],
            "ast.data.json": [WILL_ERROR],
            "babel": {
                "core.meta.json": [WILL_ERROR],
                "plural.meta.json": [WILL_ERROR],
                "messages": {
                    "catalog.meta.json": [WILL_ERROR],
                    "pofile.data.json": [WILL_ERROR],
                    "pofile.meta.json": [WILL_ERROR],
                    "catalog.data.json": [WILL_ERROR],
                    "mofile.meta.json": [WILL_ERROR],
                    "plurals.meta.json": [WILL_ERROR],
                    "__init__.meta.json": [WILL_ERROR],
                    "checkers.data.json": [WILL_ERROR],
                    "checkers.meta.json": [WILL_ERROR],
                    "__init__.data.json": [WILL_ERROR],
                    "plurals.data.json": [WILL_ERROR],
                    "mofile.data.json": [WILL_ERROR],
                },
                "plural.data.json": [WILL_ERROR],
                "localtime": {
                    "_fallback.meta.json": [WILL_ERROR],
                    "_fallback.data.json": [WILL_ERROR],
                    "_helpers.meta.json": [WILL_ERROR],
                    "__init__.meta.json": [WILL_ERROR],
                    "_unix.data.json": [WILL_ERROR],
                    "_unix.meta.json": [WILL_ERROR],
                    "__init__.data.json": [WILL_ERROR],
                    "_helpers.data.json": [WILL_ERROR],
                },
                "core.data.json": [WILL_ERROR],
                "localedata.data.json": [WILL_ERROR],
                "__init__.meta.json": [WILL_ERROR],
                "dates.meta.json": [WILL_ERROR],
                "util.meta.json": [WILL_ERROR],
                "util.data.json": [WILL_ERROR],
                "dates.data.json": [WILL_ERROR],
                "localedata.meta.json": [WILL_ERROR],
                "__init__.data.json": [WILL_ERROR],
            },
            "threading.data.json": [WILL_ERROR],
            "bisect.data.json": [WILL_ERROR],
            "copy.data.json": [WILL_ERROR],
            "functools.data.json": [WILL_ERROR],
            "tomli": {
                "_types.data.json": [WILL_ERROR],
                "_types.meta.json": [WILL_ERROR],
                "_parser.meta.json": [WILL_ERROR],
                "_re.data.json": [WILL_ERROR],
                "__init__.meta.json": [WILL_ERROR],
                "__init__.data.json": [WILL_ERROR],
                "_re.meta.json": [WILL_ERROR],
                "_parser.data.json": [WILL_ERROR],
            },
            "locale.data.json": [WILL_ERROR],
            "unicodedata.data.json": [WILL_ERROR],
            "_ast.meta.json": [WILL_ERROR],
            "weakref.data.json": [WILL_ERROR],
            "reprlib.meta.json": [WILL_ERROR],
            "sre_parse.meta.json": [WILL_ERROR],
            "sys": {
                "__init__.meta.json": [WILL_ERROR],
                "__init__.data.json": [WILL_ERROR],
            },
            "msvcrt.meta.json": [WILL_ERROR],
            "keyword.data.json": [WILL_ERROR],
            "_collections_abc.meta.json": [WILL_ERROR],
            "json": {
                "decoder.data.json": [WILL_ERROR],
                "__init__.meta.json": [WILL_ERROR],
                "encoder.data.json": [WILL_ERROR],
                "encoder.meta.json": [WILL_ERROR],
                "__init__.data.json": [WILL_ERROR],
                "decoder.meta.json": [WILL_ERROR],
            },
            "bz2.meta.json": [WILL_ERROR],
            "docsig": {
                "_hooks.data.json": [WILL_ERROR],
                "_version.data.json": [WILL_ERROR],
                "_stub.meta.json": [WILL_ERROR],
                "_display.data.json": [WILL_ERROR],
                "_core.meta.json": [WILL_ERROR],
                "__main__.data.json": [WILL_ERROR],
                "_config.meta.json": [WILL_ERROR],
                "_utils.meta.json": [WILL_ERROR],
                "_message.data.json": [WILL_ERROR],
                "messages.meta.json": [WILL_ERROR],
                "_decorators.meta.json": [WILL_ERROR],
                "_main.data.json": [WILL_ERROR],
                "_main.meta.json": [WILL_ERROR],
                "_decorators.data.json": [WILL_ERROR],
                "messages.data.json": [WILL_ERROR],
                "_utils.data.json": [WILL_ERROR],
                "_message.meta.json": [WILL_ERROR],
                "__main__.meta.json": [WILL_ERROR],
                "_config.data.json": [WILL_ERROR],
                "_core.data.json": [WILL_ERROR],
                "_stub.data.json": [WILL_ERROR],
                "_display.meta.json": [WILL_ERROR],
                "_version.meta.json": [WILL_ERROR],
                "_hooks.meta.json": [WILL_ERROR],
                "_directives.data.json": [WILL_ERROR],
                "__init__.meta.json": [WILL_ERROR],
                "_module.data.json": [WILL_ERROR],
                "_report.data.json": [WILL_ERROR],
                "_report.meta.json": [WILL_ERROR],
                "_module.meta.json": [WILL_ERROR],
                "__init__.data.json": [WILL_ERROR],
                "_directives.meta.json": [WILL_ERROR],
            },
            "math.meta.json": [WILL_ERROR],
            "heapq.data.json": [WILL_ERROR],
            "doctest.data.json": [WILL_ERROR],
            "__future__.meta.json": [WILL_ERROR],
            "string.data.json": [WILL_ERROR],
            "tempfile.meta.json": [WILL_ERROR],
            "gzip.meta.json": [WILL_ERROR],
            "uuid.data.json": [WILL_ERROR],
            "_random.meta.json": [WILL_ERROR],
            "http": {
                "__init__.meta.json": [WILL_ERROR],
                "client.data.json": [WILL_ERROR],
                "client.meta.json": [WILL_ERROR],
                "__init__.data.json": [WILL_ERROR],
            },
            "signal.meta.json": [WILL_ERROR],
            "sphinx": {
                "directives": {
                    "__init__.meta.json": [WILL_ERROR],
                    "__init__.data.json": [WILL_ERROR],
                },
                "theming.meta.json": [WILL_ERROR],
                "parsers.data.json": [WILL_ERROR],
                "events.meta.json": [WILL_ERROR],
                "addnodes.data.json": [WILL_ERROR],
                "extension.meta.json": [WILL_ERROR],
                "jinja2glue.data.json": [WILL_ERROR],
                "domains": {
                    "cpp.data.json": [WILL_ERROR],
                    "python.data.json": [WILL_ERROR],
                    "index.meta.json": [WILL_ERROR],
                    "changeset.meta.json": [WILL_ERROR],
                    "changeset.data.json": [WILL_ERROR],
                    "index.data.json": [WILL_ERROR],
                    "python.meta.json": [WILL_ERROR],
                    "cpp.meta.json": [WILL_ERROR],
                    "std.data.json": [WILL_ERROR],
                    "javascript.meta.json": [WILL_ERROR],
                    "c.data.json": [WILL_ERROR],
                    "math.meta.json": [WILL_ERROR],
                    "__init__.meta.json": [WILL_ERROR],
                    "rst.data.json": [WILL_ERROR],
                    "citation.data.json": [WILL_ERROR],
                    "citation.meta.json": [WILL_ERROR],
                    "rst.meta.json": [WILL_ERROR],
                    "c.meta.json": [WILL_ERROR],
                    "math.data.json": [WILL_ERROR],
                    "__init__.data.json": [WILL_ERROR],
                    "std.meta.json": [WILL_ERROR],
                    "javascript.data.json": [WILL_ERROR],
                },
                "locale": {
                    "__init__.meta.json": [WILL_ERROR],
                    "__init__.data.json": [WILL_ERROR],
                },
                "highlighting.meta.json": [WILL_ERROR],
                "project.meta.json": [WILL_ERROR],
                "versioning.data.json": [WILL_ERROR],
                "writers": {
                    "html5.meta.json": [WILL_ERROR],
                    "latex.meta.json": [WILL_ERROR],
                    "html5.data.json": [WILL_ERROR],
                    "latex.data.json": [WILL_ERROR],
                    "__init__.meta.json": [WILL_ERROR],
                    "html.data.json": [WILL_ERROR],
                    "html.meta.json": [WILL_ERROR],
                    "__init__.data.json": [WILL_ERROR],
                },
                "util": {
                    "tags.data.json": [WILL_ERROR],
                    "logging.data.json": [WILL_ERROR],
                    "i18n.data.json": [WILL_ERROR],
                    "http_date.meta.json": [WILL_ERROR],
                    "docutils.meta.json": [WILL_ERROR],
                    "typing.data.json": [WILL_ERROR],
                    "nodes.meta.json": [WILL_ERROR],
                    "display.data.json": [WILL_ERROR],
                    "display.meta.json": [WILL_ERROR],
                    "nodes.data.json": [WILL_ERROR],
                    "typing.meta.json": [WILL_ERROR],
                    "http_date.data.json": [WILL_ERROR],
                    "docutils.data.json": [WILL_ERROR],
                    "i18n.meta.json": [WILL_ERROR],
                    "tags.meta.json": [WILL_ERROR],
                    "logging.meta.json": [WILL_ERROR],
                    "inventory.meta.json": [WILL_ERROR],
                    "docfields.data.json": [WILL_ERROR],
                    "console.data.json": [WILL_ERROR],
                    "cfamily.meta.json": [WILL_ERROR],
                    "parallel.data.json": [WILL_ERROR],
                    "template.meta.json": [WILL_ERROR],
                    "matching.meta.json": [WILL_ERROR],
                    "math.meta.json": [WILL_ERROR],
                    "__init__.meta.json": [WILL_ERROR],
                    "exceptions.meta.json": [WILL_ERROR],
                    "images.meta.json": [WILL_ERROR],
                    "texescape.meta.json": [WILL_ERROR],
                    "rst.data.json": [WILL_ERROR],
                    "fileutil.meta.json": [WILL_ERROR],
                    "docstrings.meta.json": [WILL_ERROR],
                    "osutil.meta.json": [WILL_ERROR],
                    "build_phase.meta.json": [WILL_ERROR],
                    "inspect.data.json": [WILL_ERROR],
                    "build_phase.data.json": [WILL_ERROR],
                    "inspect.meta.json": [WILL_ERROR],
                    "osutil.data.json": [WILL_ERROR],
                    "exceptions.data.json": [WILL_ERROR],
                    "texescape.data.json": [WILL_ERROR],
                    "images.data.json": [WILL_ERROR],
                    "fileutil.data.json": [WILL_ERROR],
                    "rst.meta.json": [WILL_ERROR],
                    "docstrings.data.json": [WILL_ERROR],
                    "template.data.json": [WILL_ERROR],
                    "math.data.json": [WILL_ERROR],
                    "matching.data.json": [WILL_ERROR],
                    "__init__.data.json": [WILL_ERROR],
                    "cfamily.data.json": [WILL_ERROR],
                    "parallel.meta.json": [WILL_ERROR],
                    "console.meta.json": [WILL_ERROR],
                    "inventory.data.json": [WILL_ERROR],
                    "docfields.meta.json": [WILL_ERROR],
                },
                "builders": {
                    "gettext.meta.json": [WILL_ERROR],
                    "gettext.data.json": [WILL_ERROR],
                    "latex": {
                        "theming.meta.json": [WILL_ERROR],
                        "nodes.meta.json": [WILL_ERROR],
                        "nodes.data.json": [WILL_ERROR],
                        "theming.data.json": [WILL_ERROR],
                        "constants.data.json": [WILL_ERROR],
                        "__init__.meta.json": [WILL_ERROR],
                        "util.meta.json": [WILL_ERROR],
                        "util.data.json": [WILL_ERROR],
                        "__init__.data.json": [WILL_ERROR],
                        "constants.meta.json": [WILL_ERROR],
                    },
                    "html": {
                        "__init__.meta.json": [WILL_ERROR],
                        "__init__.data.json": [WILL_ERROR],
                    },
                    "__init__.meta.json": [WILL_ERROR],
                    "__init__.data.json": [WILL_ERROR],
                },
                "versioning.meta.json": [WILL_ERROR],
                "highlighting.data.json": [WILL_ERROR],
                "ext": {
                    "autodoc": {
                        "importer.meta.json": [WILL_ERROR],
                        "directive.meta.json": [WILL_ERROR],
                        "mock.meta.json": [WILL_ERROR],
                        "mock.data.json": [WILL_ERROR],
                        "importer.data.json": [WILL_ERROR],
                        "directive.data.json": [WILL_ERROR],
                        "__init__.meta.json": [WILL_ERROR],
                        "__init__.data.json": [WILL_ERROR],
                    },
                    "duration.data.json": [WILL_ERROR],
                    "duration.meta.json": [WILL_ERROR],
                    "__init__.meta.json": [WILL_ERROR],
                    "todo.data.json": [WILL_ERROR],
                    "napoleon": {
                        "docstring.meta.json": [WILL_ERROR],
                        "docstring.data.json": [WILL_ERROR],
                        "__init__.meta.json": [WILL_ERROR],
                        "__init__.data.json": [WILL_ERROR],
                    },
                    "todo.meta.json": [WILL_ERROR],
                    "__init__.data.json": [WILL_ERROR],
                },
                "project.data.json": [WILL_ERROR],
                "pycode": {
                    "parser.data.json": [WILL_ERROR],
                    "parser.meta.json": [WILL_ERROR],
                    "ast.data.json": [WILL_ERROR],
                    "__init__.meta.json": [WILL_ERROR],
                    "__init__.data.json": [WILL_ERROR],
                    "ast.meta.json": [WILL_ERROR],
                },
                "addnodes.meta.json": [WILL_ERROR],
                "jinja2glue.meta.json": [WILL_ERROR],
                "extension.data.json": [WILL_ERROR],
                "events.data.json": [WILL_ERROR],
                "parsers.meta.json": [WILL_ERROR],
                "theming.data.json": [WILL_ERROR],
                "search": {
                    "en.meta.json": [WILL_ERROR],
                    "en.data.json": [WILL_ERROR],
                    "__init__.meta.json": [WILL_ERROR],
                    "__init__.data.json": [WILL_ERROR],
                },
                "io.data.json": [WILL_ERROR],
                "testing": {
                    "path.data.json": [WILL_ERROR],
                    "path.meta.json": [WILL_ERROR],
                    "__init__.meta.json": [WILL_ERROR],
                    "__init__.data.json": [WILL_ERROR],
                },
                "errors.data.json": [WILL_ERROR],
                "transforms": {
                    "i18n.data.json": [WILL_ERROR],
                    "references.meta.json": [WILL_ERROR],
                    "references.data.json": [WILL_ERROR],
                    "i18n.meta.json": [WILL_ERROR],
                    "__init__.meta.json": [WILL_ERROR],
                    "post_transforms": {
                        "__init__.meta.json": [WILL_ERROR],
                        "__init__.data.json": [WILL_ERROR],
                    },
                    "__init__.data.json": [WILL_ERROR],
                },
                "registry.data.json": [WILL_ERROR],
                "__init__.meta.json": [WILL_ERROR],
                "pygments_styles.data.json": [WILL_ERROR],
                "config.data.json": [WILL_ERROR],
                "application.data.json": [WILL_ERROR],
                "deprecation.data.json": [WILL_ERROR],
                "roles.data.json": [WILL_ERROR],
                "environment": {
                    "collectors": {
                        "__init__.meta.json": [WILL_ERROR],
                        "__init__.data.json": [WILL_ERROR],
                    },
                    "adapters": {
                        "toctree.meta.json": [WILL_ERROR],
                        "toctree.data.json": [WILL_ERROR],
                        "__init__.meta.json": [WILL_ERROR],
                        "indexentries.data.json": [WILL_ERROR],
                        "asset.meta.json": [WILL_ERROR],
                        "asset.data.json": [WILL_ERROR],
                        "indexentries.meta.json": [WILL_ERROR],
                        "__init__.data.json": [WILL_ERROR],
                    },
                    "__init__.meta.json": [WILL_ERROR],
                    "__init__.data.json": [WILL_ERROR],
                },
                "deprecation.meta.json": [WILL_ERROR],
                "roles.meta.json": [WILL_ERROR],
                "application.meta.json": [WILL_ERROR],
                "config.meta.json": [WILL_ERROR],
                "pygments_styles.meta.json": [WILL_ERROR],
                "registry.meta.json": [WILL_ERROR],
                "__init__.data.json": [WILL_ERROR],
                "errors.meta.json": [WILL_ERROR],
                "io.meta.json": [WILL_ERROR],
            },
            "filecmp.data.json": [WILL_ERROR],
            "_weakref.data.json": [WILL_ERROR],
            "struct.meta.json": [WILL_ERROR],
            "sre_constants.meta.json": [WILL_ERROR],
            "_csv.data.json": [WILL_ERROR],
            "marshal.meta.json": [WILL_ERROR],
            "concurrent": {
                "futures": {
                    "_base.data.json": [WILL_ERROR],
                    "process.meta.json": [WILL_ERROR],
                    "thread.meta.json": [WILL_ERROR],
                    "thread.data.json": [WILL_ERROR],
                    "_base.meta.json": [WILL_ERROR],
                    "process.data.json": [WILL_ERROR],
                    "__init__.meta.json": [WILL_ERROR],
                    "__init__.data.json": [WILL_ERROR],
                },
                "__init__.meta.json": [WILL_ERROR],
                "__init__.data.json": [WILL_ERROR],
            },
            "_stat.meta.json": [WILL_ERROR],
            "array.meta.json": [WILL_ERROR],
            "cmd.data.json": [WILL_ERROR],
            "_thread.data.json": [WILL_ERROR],
            "fnmatch.meta.json": [WILL_ERROR],
            "pickle.meta.json": [WILL_ERROR],
            "inspect.data.json": [WILL_ERROR],
            "_compression.meta.json": [WILL_ERROR],
            "_operator.data.json": [WILL_ERROR],
            "sysconfig.meta.json": [WILL_ERROR],
            "operator.data.json": [WILL_ERROR],
            "types.data.json": [WILL_ERROR],
            "pluggy": {
                "_hooks.data.json": [WILL_ERROR],
                "_version.data.json": [WILL_ERROR],
                "_manager.data.json": [WILL_ERROR],
                "_tracing.data.json": [WILL_ERROR],
                "_result.meta.json": [WILL_ERROR],
                "_result.data.json": [WILL_ERROR],
                "_manager.meta.json": [WILL_ERROR],
                "_tracing.meta.json": [WILL_ERROR],
                "_version.meta.json": [WILL_ERROR],
                "_hooks.meta.json": [WILL_ERROR],
                "_warnings.meta.json": [WILL_ERROR],
                "_callers.meta.json": [WILL_ERROR],
                "__init__.meta.json": [WILL_ERROR],
                "__init__.data.json": [WILL_ERROR],
                "_callers.data.json": [WILL_ERROR],
                "_warnings.data.json": [WILL_ERROR],
            },
            "zipfile.data.json": [WILL_ERROR],
            "arcon": {
                "_version.data.json": [WILL_ERROR],
                "_version.meta.json": [WILL_ERROR],
                "__init__.meta.json": [WILL_ERROR],
                "__init__.data.json": [WILL_ERROR],
            },
            "bdb.data.json": [WILL_ERROR],
            "_socket.data.json": [WILL_ERROR],
            "stat.meta.json": [WILL_ERROR],
            "copyreg.data.json": [WILL_ERROR],
            "numbers.data.json": [WILL_ERROR],
            "re.meta.json": [WILL_ERROR],
            "csv.meta.json": [WILL_ERROR],
            "_socket.meta.json": [WILL_ERROR],
            "bdb.meta.json": [WILL_ERROR],
            "os": {
                "path.data.json": [WILL_ERROR],
                "path.meta.json": [WILL_ERROR],
                "__init__.meta.json": [WILL_ERROR],
                "__init__.data.json": [WILL_ERROR],
            },
            "copyreg.meta.json": [WILL_ERROR],
            "stat.data.json": [WILL_ERROR],
            "numbers.meta.json": [WILL_ERROR],
            "re.data.json": [WILL_ERROR],
            "csv.data.json": [WILL_ERROR],
            "_compression.data.json": [WILL_ERROR],
            "inspect.meta.json": [WILL_ERROR],
            "pickle.data.json": [WILL_ERROR],
            "operator.meta.json": [WILL_ERROR],
            "_operator.meta.json": [WILL_ERROR],
            "sysconfig.data.json": [WILL_ERROR],
            "zipfile.meta.json": [WILL_ERROR],
            "types.meta.json": [WILL_ERROR],
            "marshal.data.json": [WILL_ERROR],
            "_stat.data.json": [WILL_ERROR],
            "importlib": {
                "abc.meta.json": [WILL_ERROR],
                "machinery.data.json": [WILL_ERROR],
                "abc.data.json": [WILL_ERROR],
                "machinery.meta.json": [WILL_ERROR],
                "__init__.meta.json": [WILL_ERROR],
                "util.meta.json": [WILL_ERROR],
                "util.data.json": [WILL_ERROR],
                "__init__.data.json": [WILL_ERROR],
                "metadata": {
                    "__init__.meta.json": [WILL_ERROR],
                    "__init__.data.json": [WILL_ERROR],
                },
            },
            "_thread.meta.json": [WILL_ERROR],
            "fnmatch.data.json": [WILL_ERROR],
            "cmd.meta.json": [WILL_ERROR],
            "array.data.json": [WILL_ERROR],
            "signal.data.json": [WILL_ERROR],
            "filecmp.meta.json": [WILL_ERROR],
            "_weakref.meta.json": [WILL_ERROR],
            "sre_constants.data.json": [WILL_ERROR],
            "struct.data.json": [WILL_ERROR],
            "collections": {
                "abc.meta.json": [WILL_ERROR],
                "abc.data.json": [WILL_ERROR],
                "__init__.meta.json": [WILL_ERROR],
                "__init__.data.json": [WILL_ERROR],
            },
            "_csv.meta.json": [WILL_ERROR],
            "iniconfig": {
                "_parse.data.json": [WILL_ERROR],
                "_parse.meta.json": [WILL_ERROR],
                "__init__.meta.json": [WILL_ERROR],
                "exceptions.meta.json": [WILL_ERROR],
                "exceptions.data.json": [WILL_ERROR],
                "__init__.data.json": [WILL_ERROR],
            },
            "math.data.json": [WILL_ERROR],
            "__future__.data.json": [WILL_ERROR],
            "doctest.meta.json": [WILL_ERROR],
            "heapq.meta.json": [WILL_ERROR],
            "_random.data.json": [WILL_ERROR],
            "uuid.meta.json": [WILL_ERROR],
            "tempfile.data.json": [WILL_ERROR],
            "string.meta.json": [WILL_ERROR],
            "gzip.data.json": [WILL_ERROR],
            "reprlib.data.json": [WILL_ERROR],
            "weakref.meta.json": [WILL_ERROR],
            "asyncio": {
                "queues.meta.json": [WILL_ERROR],
                "events.meta.json": [WILL_ERROR],
                "transports.data.json": [WILL_ERROR],
                "subprocess.meta.json": [WILL_ERROR],
                "tasks.data.json": [WILL_ERROR],
                "protocols.meta.json": [WILL_ERROR],
                "selector_events.meta.json": [WILL_ERROR],
                "selector_events.data.json": [WILL_ERROR],
                "subprocess.data.json": [WILL_ERROR],
                "tasks.meta.json": [WILL_ERROR],
                "protocols.data.json": [WILL_ERROR],
                "events.data.json": [WILL_ERROR],
                "transports.meta.json": [WILL_ERROR],
                "queues.data.json": [WILL_ERROR],
                "futures.data.json": [WILL_ERROR],
                "streams.meta.json": [WILL_ERROR],
                "runners.data.json": [WILL_ERROR],
                "unix_events.meta.json": [WILL_ERROR],
                "locks.data.json": [WILL_ERROR],
                "__init__.meta.json": [WILL_ERROR],
                "coroutines.meta.json": [WILL_ERROR],
                "exceptions.meta.json": [WILL_ERROR],
                "base_events.data.json": [WILL_ERROR],
                "base_events.meta.json": [WILL_ERROR],
                "coroutines.data.json": [WILL_ERROR],
                "exceptions.data.json": [WILL_ERROR],
                "unix_events.data.json": [WILL_ERROR],
                "locks.meta.json": [WILL_ERROR],
                "__init__.data.json": [WILL_ERROR],
                "streams.data.json": [WILL_ERROR],
                "runners.meta.json": [WILL_ERROR],
                "futures.meta.json": [WILL_ERROR],
            },
            "unicodedata.meta.json": [WILL_ERROR],
            "_ast.data.json": [WILL_ERROR],
            "keyword.meta.json": [WILL_ERROR],
            "_collections_abc.data.json": [WILL_ERROR],
            "logging": {
                "handlers.data.json": [WILL_ERROR],
                "__init__.meta.json": [WILL_ERROR],
                "handlers.meta.json": [WILL_ERROR],
                "__init__.data.json": [WILL_ERROR],
            },
            "sre_parse.data.json": [WILL_ERROR],
            "msvcrt.data.json": [WILL_ERROR],
            "bz2.data.json": [WILL_ERROR],
            "email": {
                "header.meta.json": [WILL_ERROR],
                "charset.meta.json": [WILL_ERROR],
                "message.data.json": [WILL_ERROR],
                "message.meta.json": [WILL_ERROR],
                "charset.data.json": [WILL_ERROR],
                "header.data.json": [WILL_ERROR],
                "errors.data.json": [WILL_ERROR],
                "utils.meta.json": [WILL_ERROR],
                "__init__.meta.json": [WILL_ERROR],
                "policy.data.json": [WILL_ERROR],
                "contentmanager.data.json": [WILL_ERROR],
                "contentmanager.meta.json": [WILL_ERROR],
                "policy.meta.json": [WILL_ERROR],
                "utils.data.json": [WILL_ERROR],
                "__init__.data.json": [WILL_ERROR],
                "errors.meta.json": [WILL_ERROR],
            },
            "ast.meta.json": [WILL_ERROR],
            "tokenize.meta.json": [WILL_ERROR],
            "threading.meta.json": [WILL_ERROR],
            "bisect.meta.json": [WILL_ERROR],
            "copy.meta.json": [WILL_ERROR],
            "locale.meta.json": [WILL_ERROR],
            "functools.meta.json": [WILL_ERROR],
            "_pytest": {
                "_version.data.json": [WILL_ERROR],
                "scope.meta.json": [WILL_ERROR],
                "compat.meta.json": [WILL_ERROR],
                "logging.data.json": [WILL_ERROR],
                "python.data.json": [WILL_ERROR],
                "capture.data.json": [WILL_ERROR],
                "python_api.meta.json": [WILL_ERROR],
                "_argcomplete.data.json": [WILL_ERROR],
                "outcomes.data.json": [WILL_ERROR],
                "terminal.data.json": [WILL_ERROR],
                "timing.data.json": [WILL_ERROR],
                "main.data.json": [WILL_ERROR],
                "hookspec.meta.json": [WILL_ERROR],
                "deprecated.data.json": [WILL_ERROR],
                "recwarn.data.json": [WILL_ERROR],
                "nodes.meta.json": [WILL_ERROR],
                "tmpdir.data.json": [WILL_ERROR],
                "monkeypatch.data.json": [WILL_ERROR],
                "config": {
                    "compat.meta.json": [WILL_ERROR],
                    "argparsing.meta.json": [WILL_ERROR],
                    "argparsing.data.json": [WILL_ERROR],
                    "compat.data.json": [WILL_ERROR],
                    "findpaths.meta.json": [WILL_ERROR],
                    "__init__.meta.json": [WILL_ERROR],
                    "exceptions.meta.json": [WILL_ERROR],
                    "exceptions.data.json": [WILL_ERROR],
                    "__init__.data.json": [WILL_ERROR],
                    "findpaths.data.json": [WILL_ERROR],
                },
                "helpconfig.data.json": [WILL_ERROR],
                "monkeypatch.meta.json": [WILL_ERROR],
                "helpconfig.meta.json": [WILL_ERROR],
                "recwarn.meta.json": [WILL_ERROR],
                "nodes.data.json": [WILL_ERROR],
                "tmpdir.meta.json": [WILL_ERROR],
                "main.meta.json": [WILL_ERROR],
                "deprecated.meta.json": [WILL_ERROR],
                "hookspec.data.json": [WILL_ERROR],
                "terminal.meta.json": [WILL_ERROR],
                "timing.meta.json": [WILL_ERROR],
                "python_api.data.json": [WILL_ERROR],
                "_argcomplete.meta.json": [WILL_ERROR],
                "outcomes.meta.json": [WILL_ERROR],
                "mark": {
                    "structures.meta.json": [WILL_ERROR],
                    "structures.data.json": [WILL_ERROR],
                    "expression.meta.json": [WILL_ERROR],
                    "__init__.meta.json": [WILL_ERROR],
                    "expression.data.json": [WILL_ERROR],
                    "__init__.data.json": [WILL_ERROR],
                },
                "logging.meta.json": [WILL_ERROR],
                "python.meta.json": [WILL_ERROR],
                "capture.meta.json": [WILL_ERROR],
                "scope.data.json": [WILL_ERROR],
                "compat.data.json": [WILL_ERROR],
                "_code": {
                    "code.meta.json": [WILL_ERROR],
                    "code.data.json": [WILL_ERROR],
                    "source.meta.json": [WILL_ERROR],
                    "__init__.meta.json": [WILL_ERROR],
                    "__init__.data.json": [WILL_ERROR],
                    "source.data.json": [WILL_ERROR],
                },
                "assertion": {
                    "rewrite.meta.json": [WILL_ERROR],
                    "rewrite.data.json": [WILL_ERROR],
                    "truncate.data.json": [WILL_ERROR],
                    "__init__.meta.json": [WILL_ERROR],
                    "util.meta.json": [WILL_ERROR],
                    "util.data.json": [WILL_ERROR],
                    "__init__.data.json": [WILL_ERROR],
                    "truncate.meta.json": [WILL_ERROR],
                },
                "_version.meta.json": [WILL_ERROR],
                "warnings.meta.json": [WILL_ERROR],
                "pathlib.data.json": [WILL_ERROR],
                "freeze_support.data.json": [WILL_ERROR],
                "pytester_assertions.meta.json": [WILL_ERROR],
                "legacypath.data.json": [WILL_ERROR],
                "cacheprovider.data.json": [WILL_ERROR],
                "_io": {
                    "terminalwriter.meta.json": [WILL_ERROR],
                    "saferepr.meta.json": [WILL_ERROR],
                    "saferepr.data.json": [WILL_ERROR],
                    "terminalwriter.data.json": [WILL_ERROR],
                    "pprint.meta.json": [WILL_ERROR],
                    "wcwidth.meta.json": [WILL_ERROR],
                    "__init__.meta.json": [WILL_ERROR],
                    "wcwidth.data.json": [WILL_ERROR],
                    "__init__.data.json": [WILL_ERROR],
                    "pprint.data.json": [WILL_ERROR],
                },
                "reports.meta.json": [WILL_ERROR],
                "stash.meta.json": [WILL_ERROR],
                "doctest.data.json": [WILL_ERROR],
                "__init__.meta.json": [WILL_ERROR],
                "runner.data.json": [WILL_ERROR],
                "warning_types.data.json": [WILL_ERROR],
                "debugging.meta.json": [WILL_ERROR],
                "fixtures.data.json": [WILL_ERROR],
                "pytester.data.json": [WILL_ERROR],
                "fixtures.meta.json": [WILL_ERROR],
                "pytester.meta.json": [WILL_ERROR],
                "runner.meta.json": [WILL_ERROR],
                "warning_types.meta.json": [WILL_ERROR],
                "debugging.data.json": [WILL_ERROR],
                "cacheprovider.meta.json": [WILL_ERROR],
                "reports.data.json": [WILL_ERROR],
                "stash.data.json": [WILL_ERROR],
                "doctest.meta.json": [WILL_ERROR],
                "__init__.data.json": [WILL_ERROR],
                "pytester_assertions.data.json": [WILL_ERROR],
                "legacypath.meta.json": [WILL_ERROR],
                "freeze_support.meta.json": [WILL_ERROR],
                "pathlib.meta.json": [WILL_ERROR],
                "warnings.data.json": [WILL_ERROR],
            },
            "selectors.data.json": [WILL_ERROR],
            "pprint.data.json": [WILL_ERROR],
            "sre_compile.data.json": [WILL_ERROR],
            "io.meta.json": [WILL_ERROR],
            "tty.meta.json": [WILL_ERROR],
            "codecs.meta.json": [WILL_ERROR],
            "typing_extensions.data.json": [WILL_ERROR],
            "_warnings.data.json": [WILL_ERROR],
            "pathlib.meta.json": [WILL_ERROR],
            "warnings.data.json": [WILL_ERROR],
        },
    },
    ".gitignore": [
        "*build/",
        "*coverage*",
        "*venv",
        ".DS_Store",
        ".env",
        "__pycache__/",
        "dist/",
        "node_modules/",
    ],
    "package-lock.json": [WILL_ERROR],
    "package.json": [WILL_ERROR],
    "CONTRIBUTING.md": [WILL_ERROR],
    ".github": {
        "COMMIT_POLICY.md": [WILL_ERROR],
        "workflows": {
            "codeql-analysis.yml": [WILL_ERROR],
            "build.yaml": [WILL_ERROR],
        },
        "dependabot.yml": [WILL_ERROR],
    },
    "coverage.xml": [WILL_ERROR],
    "poetry.lock": [WILL_ERROR],
    "README.rst": [WILL_ERROR],
    ".git": {
        "HEAD": [WILL_ERROR],
    },
    ".idea": {
        "docsig.iml": [WILL_ERROR],
        "jsonSchemas.xml": [WILL_ERROR],
        "inspectionProfiles": {
            "profiles_settings.xml": [WILL_ERROR],
            "Project_Default.xml": [WILL_ERROR],
        },
        "codeStyles": {
            "Project.xml": [WILL_ERROR],
            "codeStyleConfig.xml": [WILL_ERROR],
        },
        "material_theme_project_new.xml": [WILL_ERROR],
        "vcs.xml": [WILL_ERROR],
        ".gitignore": [
            "/dataSources.local.xml",
            "/dataSources/",
            "/dictionaries",
            "/httpRequests/",
            "/shelf/",
            "/sonarlint/",
            "/tasks.xml",
            "/usage.statistics.xml",
            "/workspace.xml",
        ],
        "workspace.xml": [WILL_ERROR],
        "modules.xml": [WILL_ERROR],
        "watcherTasks.xml": [WILL_ERROR],
        "dictionaries": {
            "swhitlock.xml": [WILL_ERROR],
            "default_user.xml": [WILL_ERROR],
        },
        "misc.xml": [WILL_ERROR],
        "scopes": {
            "whitelist_py.xml": [WILL_ERROR],
            "bump2version.xml": [WILL_ERROR],
            "docs__themes_graphite_static.xml": [WILL_ERROR],
            "docs_conf.xml": [WILL_ERROR],
            "_prettierignore.xml": [WILL_ERROR],
            "docs_index.xml": [WILL_ERROR],
            "_pylintrc.xml": [WILL_ERROR],
        },
    },
}
