"""
tests.exclude_test
==================
"""

# pylint: disable=too-many-lines,line-too-long

from __future__ import annotations

from pathlib import Path

import pytest

from . import FixtureMakeTree, InitFileFixtureType, MockMainType, long

TREE = {
    ".pyaud_cache": {
        "7.5.1": {
            "CACHEDIR.TAG": [],
            "files.json": "",
            ".gitignore": ["*"],
        }
    },
    "CODE_OF_CONDUCT.md": [],
    ".pylintrc": [],
    "LICENSE": [],
    ".pytest_cache": {
        "CACHEDIR.TAG": [],
        "README.md": [],
        ".gitignore": ["*"],
        "v": {
            "cache": {"nodeids": [], "lastfailed": "", "stepwise": ""},
            "randomly_seed": [],
        },
    },
    "CHANGELOG.md": [],
    "dist": {
        "docsig-0.49.1.tar.gz": [],
        "docsig-0.49.2-py3-none-any.whl": [],
        "docsig-0.49.2.tar.gz": [],
        "docsig-0.49.0-py3-none-any.whl": [],
        "docsig-0.49.0.tar.gz": [],
        "docsig-0.49.1-py3-none-any.whl": [],
    },
    ".pre-commit-config.yaml": [],
    ".coverage": [],
    "Makefile": [],
    "whitelist.py": [],
    ".pre-commit-hooks.yaml": [],
    "pyproject.toml": [],
    ".bumpversion.cfg": [],
    "node_modules": {
        ".cache": {
            "prettier": {
                ".prettier-caches": {
                    "7f51ae3462154079bc96a79583b977616b1ad315.json": []
                }
            }
        }
    },
    "tests": {
        "misc_test.py": [],
        "conftest.py": [],
        "disable_test.py": [],
        "__init__.py": [],
        "__pycache__": {
            "_test.cpython-38-pytest-8.1.1.pyc": [],
            "__init__.cpython-38.pyc": [],
            "disable_test.cpython-38-pytest-8.1.1.pyc": [],
            "misc_test.cpython-38-pytest-8.1.1.pyc": [],
            "_test.cpython-38.pyc": [],
            "conftest.cpython-38-pytest-8.1.1.pyc": [],
        },
        "TESTS.md": [],
        "git_test.py": [],
        "_test.py": [],
    },
    ".conform.yaml": [],
    "docs": {
        "index.rst": [],
        "requirements.txt": [],
        "docsig.rst": [],
        "conf.py": [],
        "static": {"docsig.svg": []},
        "examples": {"classes.rst": [], "message-control.rst": ""},
    },
    ".readthedocs.yml": [],
    ".prettierignore": [],
    ".editorconfig": [],
    "docsig": {
        "_stub.py": [],
        "_report.py": [],
        "_main.py": [],
        "_version.py": [],
        "_module.py": [],
        "__init__.py": [],
        "_display.py": [],
        "_hooks.py": [],
        "__pycache__": {
            "_core.cpython-311.pyc": [],
            "__init__.cpython-38.pyc": [],
            "_core.cpython-38.pyc": [],
            "_main.cpython-311.pyc": [],
            "_decorators.cpython-38.pyc": [],
            "_message.cpython-311.pyc": [],
            "_config.cpython-311.pyc": [],
            "_config.cpython-38.pyc": [],
            "messages.cpython-311.pyc": [],
            "_display.cpython-311.pyc": [],
            "_display.cpython-38.pyc": [],
            "_stub.cpython-311.pyc": [],
            "_decorators.cpython-311.pyc": [],
            "_hooks.cpython-38.pyc": [],
            "_utils.cpython-38.pyc": [],
            "_report.cpython-311.pyc": [],
            "_directives.cpython-38.pyc": [],
            "_hooks.cpython-311.pyc": [],
            "__main__.cpython-38.pyc": [],
            "_version.cpython-311.pyc": [],
            "_utils.cpython-311.pyc": [],
            "_module.cpython-311.pyc": [],
            "_stub.cpython-38.pyc": [],
            "messages.cpython-38.pyc": [],
            "_message.cpython-38.pyc": [],
            "_report.cpython-38.pyc": [],
            "_version.cpython-38.pyc": [],
            "_directives.cpython-311.pyc": [],
            "_git.cpython-38.pyc": [],
            "_module.cpython-38.pyc": [],
            "_main.cpython-38.pyc": [],
            "__init__.cpython-311.pyc": [],
            "__main__.cpython-311.pyc": [],
        },
        "_message.py": [],
        "_core.py": [],
        "_decorators.py": [],
        "messages.py": [],
        "py.typed": [],
        "_config.py": [],
        "__main__.py": [],
        "_utils.py": [],
        "_directives.py": [],
    },
    ".mypy_cache": {
        "CACHEDIR.TAG": [],
        "3.12": {
            "builtins.meta.json": [],
            "genericpath.meta.json": [],
            "enum.meta.json": [],
            "abc.meta.json": [],
            "subprocess.meta.json": [],
            "dataclasses.data.json": [],
            "typing.data.json": [],
            "resource.data.json": [],
            "_codecs.meta.json": [],
            "posixpath.data.json": [],
            "contextlib.meta.json": [],
            "_codecs.data.json": [],
            "posixpath.meta.json": [],
            "contextlib.data.json": [],
            "resource.meta.json": [],
            "typing.meta.json": [],
            "_typeshed": {
                "__init__.meta.json": [],
                "__init__.data.json": [],
            },
            "abc.data.json": [],
            "subprocess.data.json": [],
            "zipfile": {
                "_path.data.json": [],
                "_path.meta.json": [],
                "__init__.meta.json": [],
                "__init__.data.json": [],
            },
            "dataclasses.meta.json": [],
            "genericpath.data.json": [],
            "enum.data.json": [],
            "builtins.data.json": [],
            "@plugins_snapshot.json": [],
            "sre_compile.meta.json": [],
            "io.data.json": [],
            "codecs.data.json": [],
            "pathlib.data.json": [],
            "typing_extensions.meta.json": [],
            "conf.meta.json": [],
            "_ast.meta.json": [],
            "sre_parse.meta.json": [],
            "sys": {
                "__init__.meta.json": [],
                "_monitoring.data.json": [],
                "_monitoring.meta.json": [],
                "__init__.data.json": [],
            },
            "_collections_abc.meta.json": [],
            "sre_constants.meta.json": [],
            "types.data.json": [],
            "re.meta.json": [],
            "os": {
                "path.data.json": [],
                "path.meta.json": [],
                "__init__.meta.json": [],
                "__init__.data.json": [],
            },
            "re.data.json": [],
            "types.meta.json": [],
            "importlib": {
                "abc.meta.json": [],
                "machinery.data.json": [],
                "_abc.data.json": [],
                "_abc.meta.json": [],
                "resources": {
                    "abc.meta.json": [],
                    "abc.data.json": [],
                    "__init__.meta.json": [],
                    "__init__.data.json": [],
                },
                "abc.data.json": [],
                "machinery.meta.json": [],
                "__init__.meta.json": [],
                "readers.meta.json": [],
                "readers.data.json": [],
                "__init__.data.json": [],
                "metadata": {
                    "__init__.meta.json": [],
                    "_meta.meta.json": [],
                    "_meta.data.json": [],
                    "__init__.data.json": [],
                },
            },
            "sre_constants.data.json": [],
            "collections": {
                "abc.meta.json": [],
                "abc.data.json": [],
                "__init__.meta.json": [],
                "__init__.data.json": [],
            },
            "_ast.data.json": [],
            "_collections_abc.data.json": [],
            "sre_parse.data.json": [],
            "email": {
                "header.meta.json": [],
                "charset.meta.json": [],
                "_policybase.meta.json": [],
                "message.data.json": [],
                "message.meta.json": [],
                "charset.data.json": [],
                "_policybase.data.json": [],
                "header.data.json": [],
                "errors.data.json": [],
                "__init__.meta.json": [],
                "policy.data.json": [],
                "contentmanager.data.json": [],
                "contentmanager.meta.json": [],
                "policy.meta.json": [],
                "__init__.data.json": [],
                "errors.meta.json": [],
            },
            "conf.data.json": [],
            "sre_compile.data.json": [],
            "io.meta.json": [],
            "codecs.meta.json": [],
            "typing_extensions.data.json": [],
            "pathlib.meta.json": [],
        },
        ".gitignore": ["*"],
        "3.8": {
            "atexit.meta.json": [],
            "datetime.data.json": [],
            "socket.meta.json": [],
            "ssl.data.json": [],
            "configparser.data.json": [],
            "packaging": {
                "tags.data.json": [],
                "_manylinux.data.json": [],
                "_elffile.data.json": [],
                "_structures.meta.json": [],
                "markers.data.json": [],
                "version.data.json": [],
                "_structures.data.json": [],
                "markers.meta.json": [],
                "version.meta.json": [],
                "_elffile.meta.json": [],
                "_manylinux.meta.json": [],
                "tags.meta.json": [],
                "_parser.meta.json": [],
                "specifiers.data.json": [],
                "utils.meta.json": [],
                "__init__.meta.json": [],
                "_tokenizer.data.json": [],
                "requirements.meta.json": [],
                "_musllinux.meta.json": [],
                "_musllinux.data.json": [],
                "requirements.data.json": [],
                "utils.data.json": [],
                "__init__.data.json": [],
                "_tokenizer.meta.json": [],
                "_parser.data.json": [],
                "specifiers.meta.json": [],
            },
            "platform.meta.json": [],
            "difflib.meta.json": [],
            "builtins.meta.json": [],
            "zlib.meta.json": [],
            "ctypes": {"__init__.meta.json": [], "__init__.data.json": ""},
            "contextvars.data.json": [],
            "time.data.json": [],
            "token.meta.json": [],
            "decimal.data.json": [],
            "markupsafe": {
                "_speedups.data.json": [],
                "_speedups.meta.json": [],
                "_native.meta.json": [],
                "__init__.meta.json": [],
                "__init__.data.json": [],
                "_native.data.json": [],
            },
            "unittest": {
                "suite.data.json": [],
                "async_case.data.json": [],
                "loader.meta.json": [],
                "main.data.json": [],
                "case.data.json": [],
                "case.meta.json": [],
                "main.meta.json": [],
                "loader.data.json": [],
                "async_case.meta.json": [],
                "suite.meta.json": [],
                "result.data.json": [],
                "__init__.meta.json": [],
                "runner.data.json": [],
                "signals.meta.json": [],
                "signals.data.json": [],
                "runner.meta.json": [],
                "__init__.data.json": [],
                "result.meta.json": [],
            },
            "opcode.meta.json": [],
            "genericpath.meta.json": [],
            "_weakrefset.data.json": [],
            "shlex.meta.json": [],
            "hashlib.meta.json": [],
            "tarfile.data.json": [],
            "fractions.data.json": [],
            "textwrap.data.json": [],
            "enum.meta.json": [],
            "_ctypes.meta.json": [],
            "abc.meta.json": [],
            "traceback.meta.json": [],
            "random.data.json": [],
            "subprocess.meta.json": [],
            "itertools.meta.json": [],
            "dataclasses.data.json": [],
            "typing.data.json": [],
            "_heapq.data.json": [],
            "gc.data.json": [],
            "_decimal.data.json": [],
            "base64.meta.json": [],
            "pdb.data.json": [],
            "queue.meta.json": [],
            "_bisect.meta.json": [],
            "_locale.meta.json": [],
            "dis.meta.json": [],
            "object_colors": {
                "_version.data.json": [],
                "_version.meta.json": [],
                "__init__.meta.json": [],
                "__init__.data.json": [],
            },
            "pytest": {"__init__.meta.json": [], "__init__.data.json": ""},
            "_codecs.meta.json": [],
            "glob.meta.json": [],
            "posixpath.data.json": [],
            "gettext.meta.json": [],
            "errno.meta.json": [],
            "argparse.data.json": [],
            "contextlib.meta.json": [],
            "shutil.meta.json": [],
            "zipimport.data.json": [],
            "termios.data.json": [],
            "_codecs.data.json": [],
            "jinja2": {
                "compiler.meta.json": [],
                "visitor.data.json": [],
                "bccache.data.json": [],
                "optimizer.meta.json": [],
                "loaders.data.json": [],
                "async_utils.meta.json": [],
                "filters.data.json": [],
                "runtime.data.json": [],
                "sandbox.meta.json": [],
                "parser.data.json": [],
                "nodes.meta.json": [],
                "tests.meta.json": [],
                "tests.data.json": [],
                "parser.meta.json": [],
                "nodes.data.json": [],
                "filters.meta.json": [],
                "async_utils.data.json": [],
                "runtime.meta.json": [],
                "sandbox.data.json": [],
                "bccache.meta.json": [],
                "optimizer.data.json": [],
                "loaders.meta.json": [],
                "compiler.data.json": [],
                "visitor.meta.json": [],
                "defaults.meta.json": [],
                "utils.meta.json": [],
                "__init__.meta.json": [],
                "exceptions.meta.json": [],
                "lexer.meta.json": [],
                "idtracking.meta.json": [],
                "environment.data.json": [],
                "ext.meta.json": [],
                "_identifier.meta.json": [],
                "debug.data.json": [],
                "_identifier.data.json": [],
                "debug.meta.json": [],
                "environment.meta.json": [],
                "ext.data.json": [],
                "exceptions.data.json": [],
                "lexer.data.json": [],
                "idtracking.data.json": [],
                "utils.data.json": [],
                "__init__.data.json": [],
                "defaults.data.json": [],
            },
            "glob.data.json": [],
            "gettext.data.json": [],
            "posixpath.meta.json": [],
            "contextlib.data.json": [],
            "shutil.data.json": [],
            "argparse.meta.json": [],
            "errno.data.json": [],
            "termios.meta.json": [],
            "zipimport.meta.json": [],
            "_bisect.data.json": [],
            "_locale.data.json": [],
            "dis.data.json": [],
            "multiprocessing": {
                "queues.meta.json": [],
                "process.meta.json": [],
                "reduction.data.json": [],
                "shared_memory.meta.json": [],
                "pool.meta.json": [],
                "managers.meta.json": [],
                "context.data.json": [],
                "popen_spawn_posix.data.json": [],
                "popen_fork.data.json": [],
                "popen_fork.meta.json": [],
                "popen_spawn_posix.meta.json": [],
                "context.meta.json": [],
                "managers.data.json": [],
                "pool.data.json": [],
                "queues.data.json": [],
                "process.data.json": [],
                "reduction.meta.json": [],
                "shared_memory.data.json": [],
                "connection.data.json": [],
                "spawn.data.json": [],
                "__init__.meta.json": [],
                "util.meta.json": [],
                "popen_spawn_win32.data.json": [],
                "synchronize.data.json": [],
                "sharedctypes.meta.json": [],
                "popen_forkserver.meta.json": [],
                "popen_forkserver.data.json": [],
                "popen_spawn_win32.meta.json": [],
                "sharedctypes.data.json": [],
                "synchronize.meta.json": [],
                "util.data.json": [],
                "__init__.data.json": [],
                "spawn.meta.json": [],
                "connection.meta.json": [],
            },
            "templatest": {
                "_version.data.json": [],
                "_collections.data.json": [],
                "_abc.data.json": [],
                "_abc.meta.json": [],
                "_collections.meta.json": [],
                "_version.meta.json": [],
                "_objects.meta.json": [],
                "templates.meta.json": [],
                "utils.meta.json": [],
                "__init__.meta.json": [],
                "exceptions.meta.json": [],
                "exceptions.data.json": [],
                "utils.data.json": [],
                "__init__.data.json": [],
                "templates.data.json": [],
                "_objects.data.json": [],
            },
            "typing.meta.json": [],
            "_heapq.meta.json": [],
            "_decimal.meta.json": [],
            "gc.meta.json": [],
            "_typeshed": {
                "__init__.meta.json": [],
                "__init__.data.json": [],
            },
            "pathspec": {
                "pathspec.data.json": [],
                "pattern.data.json": [],
                "gitignore.data.json": [],
                "patterns": {
                    "__init__.meta.json": [],
                    "gitwildmatch.meta.json": [],
                    "gitwildmatch.data.json": [],
                    "__init__.data.json": [],
                },
                "gitignore.meta.json": [],
                "pattern.meta.json": [],
                "pathspec.meta.json": [],
                "__init__.meta.json": [],
                "util.meta.json": [],
                "_meta.meta.json": [],
                "_meta.data.json": [],
                "util.data.json": [],
                "__init__.data.json": [],
            },
            "pdb.meta.json": [],
            "queue.data.json": [],
            "base64.data.json": [],
            "urllib": {
                "parse.data.json": [],
                "__init__.meta.json": [],
                "__init__.data.json": [],
                "parse.meta.json": [],
            },
            "abc.data.json": [],
            "itertools.data.json": [],
            "subprocess.data.json": [],
            "traceback.data.json": [],
            "random.meta.json": [],
            "dataclasses.meta.json": [],
            "tests": {
                "disable_test.meta.json": [],
                "disable_test.data.json": [],
                "_test.data.json": [],
                "conftest.meta.json": [],
                "__init__.meta.json": [],
                "misc_test.meta.json": [],
                "misc_test.data.json": [],
                "__init__.data.json": [],
                "conftest.data.json": [],
                "_test.meta.json": [],
            },
            "opcode.data.json": [],
            "genericpath.data.json": [],
            "decimal.meta.json": [],
            "hashlib.data.json": [],
            "shlex.data.json": [],
            "tarfile.meta.json": [],
            "_weakrefset.meta.json": [],
            "enum.data.json": [],
            "importlib_metadata": {
                "_itertools.data.json": [],
                "_adapters.data.json": [],
                "_collections.data.json": [],
                "compat": {
                    "py39.data.json": [],
                    "__init__.meta.json": [],
                    "__init__.data.json": [],
                    "py39.meta.json": [],
                },
                "_text.meta.json": [],
                "_text.data.json": [],
                "_adapters.meta.json": [],
                "_collections.meta.json": [],
                "_itertools.meta.json": [],
                "__init__.meta.json": [],
                "_meta.meta.json": [],
                "_compat.data.json": [],
                "_functools.meta.json": [],
                "_functools.data.json": [],
                "_meta.data.json": [],
                "_compat.meta.json": [],
                "__init__.data.json": [],
            },
            "textwrap.meta.json": [],
            "fractions.meta.json": [],
            "_ctypes.data.json": [],
            "click": {
                "core.meta.json": [],
                "decorators.meta.json": [],
                "formatting.data.json": [],
                "parser.data.json": [],
                "globals.data.json": [],
                "globals.meta.json": [],
                "parser.meta.json": [],
                "formatting.meta.json": [],
                "decorators.data.json": [],
                "core.data.json": [],
                "termui.meta.json": [],
                "utils.meta.json": [],
                "__init__.meta.json": [],
                "exceptions.meta.json": [],
                "_termui_impl.data.json": [],
                "shell_completion.data.json": [],
                "_compat.data.json": [],
                "types.data.json": [],
                "_compat.meta.json": [],
                "types.meta.json": [],
                "shell_completion.meta.json": [],
                "exceptions.data.json": [],
                "_termui_impl.meta.json": [],
                "utils.data.json": [],
                "__init__.data.json": [],
                "termui.data.json": [],
            },
            "zlib.data.json": [],
            "builtins.data.json": [],
            "contextvars.meta.json": [],
            "time.meta.json": [],
            "@plugins_snapshot.json": [],
            "token.data.json": [],
            "html": {"__init__.meta.json": [], "__init__.data.json": ""},
            "platform.data.json": [],
            "difflib.data.json": [],
            "datetime.meta.json": [],
            "atexit.data.json": [],
            "socket.data.json": [],
            "ssl.meta.json": [],
            "exceptiongroup": {
                "_version.data.json": [],
                "_formatting.data.json": [],
                "_catch.meta.json": [],
                "_suppress.data.json": [],
                "_suppress.meta.json": [],
                "_catch.data.json": [],
                "_version.meta.json": [],
                "_formatting.meta.json": [],
                "_exceptions.meta.json": [],
                "__init__.meta.json": [],
                "__init__.data.json": [],
                "_exceptions.data.json": [],
            },
            "configparser.meta.json": [],
            "pprint.meta.json": [],
            "sre_compile.meta.json": [],
            "selectors.meta.json": [],
            "tty.data.json": [],
            "io.data.json": [],
            "codecs.data.json": [],
            "warnings.meta.json": [],
            "pathlib.data.json": [],
            "typing_extensions.meta.json": [],
            "_warnings.meta.json": [],
            "tokenize.data.json": [],
            "ast.data.json": [],
            "babel": {
                "core.meta.json": [],
                "plural.meta.json": [],
                "messages": {
                    "catalog.meta.json": [],
                    "pofile.data.json": [],
                    "pofile.meta.json": [],
                    "catalog.data.json": [],
                    "mofile.meta.json": [],
                    "plurals.meta.json": [],
                    "__init__.meta.json": [],
                    "checkers.data.json": [],
                    "checkers.meta.json": [],
                    "__init__.data.json": [],
                    "plurals.data.json": [],
                    "mofile.data.json": [],
                },
                "plural.data.json": [],
                "localtime": {
                    "_fallback.meta.json": [],
                    "_fallback.data.json": [],
                    "_helpers.meta.json": [],
                    "__init__.meta.json": [],
                    "_unix.data.json": [],
                    "_unix.meta.json": [],
                    "__init__.data.json": [],
                    "_helpers.data.json": [],
                },
                "core.data.json": [],
                "localedata.data.json": [],
                "__init__.meta.json": [],
                "dates.meta.json": [],
                "util.meta.json": [],
                "util.data.json": [],
                "dates.data.json": [],
                "localedata.meta.json": [],
                "__init__.data.json": [],
            },
            "threading.data.json": [],
            "bisect.data.json": [],
            "copy.data.json": [],
            "functools.data.json": [],
            "tomli": {
                "_types.data.json": [],
                "_types.meta.json": [],
                "_parser.meta.json": [],
                "_re.data.json": [],
                "__init__.meta.json": [],
                "__init__.data.json": [],
                "_re.meta.json": [],
                "_parser.data.json": [],
            },
            "locale.data.json": [],
            "unicodedata.data.json": [],
            "_ast.meta.json": [],
            "weakref.data.json": [],
            "reprlib.meta.json": [],
            "sre_parse.meta.json": [],
            "sys": {"__init__.meta.json": [], "__init__.data.json": ""},
            "msvcrt.meta.json": [],
            "keyword.data.json": [],
            "_collections_abc.meta.json": [],
            "json": {
                "decoder.data.json": [],
                "__init__.meta.json": [],
                "encoder.data.json": [],
                "encoder.meta.json": [],
                "__init__.data.json": [],
                "decoder.meta.json": [],
            },
            "bz2.meta.json": [],
            "docsig": {
                "_hooks.data.json": [],
                "_version.data.json": [],
                "_stub.meta.json": [],
                "_display.data.json": [],
                "_core.meta.json": [],
                "__main__.data.json": [],
                "_config.meta.json": [],
                "_utils.meta.json": [],
                "_message.data.json": [],
                "messages.meta.json": [],
                "_decorators.meta.json": [],
                "_main.data.json": [],
                "_main.meta.json": [],
                "_decorators.data.json": [],
                "messages.data.json": [],
                "_utils.data.json": [],
                "_message.meta.json": [],
                "__main__.meta.json": [],
                "_config.data.json": [],
                "_core.data.json": [],
                "_stub.data.json": [],
                "_display.meta.json": [],
                "_version.meta.json": [],
                "_hooks.meta.json": [],
                "_directives.data.json": [],
                "__init__.meta.json": [],
                "_module.data.json": [],
                "_report.data.json": [],
                "_report.meta.json": [],
                "_module.meta.json": [],
                "__init__.data.json": [],
                "_directives.meta.json": [],
            },
            "math.meta.json": [],
            "heapq.data.json": [],
            "doctest.data.json": [],
            "__future__.meta.json": [],
            "string.data.json": [],
            "tempfile.meta.json": [],
            "gzip.meta.json": [],
            "uuid.data.json": [],
            "_random.meta.json": [],
            "http": {
                "__init__.meta.json": [],
                "client.data.json": [],
                "client.meta.json": [],
                "__init__.data.json": [],
            },
            "signal.meta.json": [],
            "sphinx": {
                "directives": {
                    "__init__.meta.json": [],
                    "__init__.data.json": [],
                },
                "theming.meta.json": [],
                "parsers.data.json": [],
                "events.meta.json": [],
                "addnodes.data.json": [],
                "extension.meta.json": [],
                "jinja2glue.data.json": [],
                "domains": {
                    "cpp.data.json": [],
                    "python.data.json": [],
                    "index.meta.json": [],
                    "changeset.meta.json": [],
                    "changeset.data.json": [],
                    "index.data.json": [],
                    "python.meta.json": [],
                    "cpp.meta.json": [],
                    "std.data.json": [],
                    "javascript.meta.json": [],
                    "c.data.json": [],
                    "math.meta.json": [],
                    "__init__.meta.json": [],
                    "rst.data.json": [],
                    "citation.data.json": [],
                    "citation.meta.json": [],
                    "rst.meta.json": [],
                    "c.meta.json": [],
                    "math.data.json": [],
                    "__init__.data.json": [],
                    "std.meta.json": [],
                    "javascript.data.json": [],
                },
                "locale": {
                    "__init__.meta.json": [],
                    "__init__.data.json": [],
                },
                "highlighting.meta.json": [],
                "project.meta.json": [],
                "versioning.data.json": [],
                "writers": {
                    "html5.meta.json": [],
                    "latex.meta.json": [],
                    "html5.data.json": [],
                    "latex.data.json": [],
                    "__init__.meta.json": [],
                    "html.data.json": [],
                    "html.meta.json": [],
                    "__init__.data.json": [],
                },
                "util": {
                    "tags.data.json": [],
                    "logging.data.json": [],
                    "i18n.data.json": [],
                    "http_date.meta.json": [],
                    "docutils.meta.json": [],
                    "typing.data.json": [],
                    "nodes.meta.json": [],
                    "display.data.json": [],
                    "display.meta.json": [],
                    "nodes.data.json": [],
                    "typing.meta.json": [],
                    "http_date.data.json": [],
                    "docutils.data.json": [],
                    "i18n.meta.json": [],
                    "tags.meta.json": [],
                    "logging.meta.json": [],
                    "inventory.meta.json": [],
                    "docfields.data.json": [],
                    "console.data.json": [],
                    "cfamily.meta.json": [],
                    "parallel.data.json": [],
                    "template.meta.json": [],
                    "matching.meta.json": [],
                    "math.meta.json": [],
                    "__init__.meta.json": [],
                    "exceptions.meta.json": [],
                    "images.meta.json": [],
                    "texescape.meta.json": [],
                    "rst.data.json": [],
                    "fileutil.meta.json": [],
                    "docstrings.meta.json": [],
                    "osutil.meta.json": [],
                    "build_phase.meta.json": [],
                    "inspect.data.json": [],
                    "build_phase.data.json": [],
                    "inspect.meta.json": [],
                    "osutil.data.json": [],
                    "exceptions.data.json": [],
                    "texescape.data.json": [],
                    "images.data.json": [],
                    "fileutil.data.json": [],
                    "rst.meta.json": [],
                    "docstrings.data.json": [],
                    "template.data.json": [],
                    "math.data.json": [],
                    "matching.data.json": [],
                    "__init__.data.json": [],
                    "cfamily.data.json": [],
                    "parallel.meta.json": [],
                    "console.meta.json": [],
                    "inventory.data.json": [],
                    "docfields.meta.json": [],
                },
                "builders": {
                    "gettext.meta.json": [],
                    "gettext.data.json": [],
                    "latex": {
                        "theming.meta.json": [],
                        "nodes.meta.json": [],
                        "nodes.data.json": [],
                        "theming.data.json": [],
                        "constants.data.json": [],
                        "__init__.meta.json": [],
                        "util.meta.json": [],
                        "util.data.json": [],
                        "__init__.data.json": [],
                        "constants.meta.json": [],
                    },
                    "html": {
                        "__init__.meta.json": [],
                        "__init__.data.json": [],
                    },
                    "__init__.meta.json": [],
                    "__init__.data.json": [],
                },
                "versioning.meta.json": [],
                "highlighting.data.json": [],
                "ext": {
                    "autodoc": {
                        "importer.meta.json": [],
                        "directive.meta.json": [],
                        "mock.meta.json": [],
                        "mock.data.json": [],
                        "importer.data.json": [],
                        "directive.data.json": [],
                        "__init__.meta.json": [],
                        "__init__.data.json": [],
                    },
                    "duration.data.json": [],
                    "duration.meta.json": [],
                    "__init__.meta.json": [],
                    "todo.data.json": [],
                    "napoleon": {
                        "docstring.meta.json": [],
                        "docstring.data.json": [],
                        "__init__.meta.json": [],
                        "__init__.data.json": [],
                    },
                    "todo.meta.json": [],
                    "__init__.data.json": [],
                },
                "project.data.json": [],
                "pycode": {
                    "parser.data.json": [],
                    "parser.meta.json": [],
                    "ast.data.json": [],
                    "__init__.meta.json": [],
                    "__init__.data.json": [],
                    "ast.meta.json": [],
                },
                "addnodes.meta.json": [],
                "jinja2glue.meta.json": [],
                "extension.data.json": [],
                "events.data.json": [],
                "parsers.meta.json": [],
                "theming.data.json": [],
                "search": {
                    "en.meta.json": [],
                    "en.data.json": [],
                    "__init__.meta.json": [],
                    "__init__.data.json": [],
                },
                "io.data.json": [],
                "testing": {
                    "path.data.json": [],
                    "path.meta.json": [],
                    "__init__.meta.json": [],
                    "__init__.data.json": [],
                },
                "errors.data.json": [],
                "transforms": {
                    "i18n.data.json": [],
                    "references.meta.json": [],
                    "references.data.json": [],
                    "i18n.meta.json": [],
                    "__init__.meta.json": [],
                    "post_transforms": {
                        "__init__.meta.json": [],
                        "__init__.data.json": [],
                    },
                    "__init__.data.json": [],
                },
                "registry.data.json": [],
                "__init__.meta.json": [],
                "pygments_styles.data.json": [],
                "config.data.json": [],
                "application.data.json": [],
                "deprecation.data.json": [],
                "roles.data.json": [],
                "environment": {
                    "collectors": {
                        "__init__.meta.json": [],
                        "__init__.data.json": [],
                    },
                    "adapters": {
                        "toctree.meta.json": [],
                        "toctree.data.json": [],
                        "__init__.meta.json": [],
                        "indexentries.data.json": [],
                        "asset.meta.json": [],
                        "asset.data.json": [],
                        "indexentries.meta.json": [],
                        "__init__.data.json": [],
                    },
                    "__init__.meta.json": [],
                    "__init__.data.json": [],
                },
                "deprecation.meta.json": [],
                "roles.meta.json": [],
                "application.meta.json": [],
                "config.meta.json": [],
                "pygments_styles.meta.json": [],
                "registry.meta.json": [],
                "__init__.data.json": [],
                "errors.meta.json": [],
                "io.meta.json": [],
            },
            "filecmp.data.json": [],
            "_weakref.data.json": [],
            "struct.meta.json": [],
            "sre_constants.meta.json": [],
            "_csv.data.json": [],
            "marshal.meta.json": [],
            "concurrent": {
                "futures": {
                    "_base.data.json": [],
                    "process.meta.json": [],
                    "thread.meta.json": [],
                    "thread.data.json": [],
                    "_base.meta.json": [],
                    "process.data.json": [],
                    "__init__.meta.json": [],
                    "__init__.data.json": [],
                },
                "__init__.meta.json": [],
                "__init__.data.json": [],
            },
            "_stat.meta.json": [],
            "array.meta.json": [],
            "cmd.data.json": [],
            "_thread.data.json": [],
            "fnmatch.meta.json": [],
            "pickle.meta.json": [],
            "inspect.data.json": [],
            "_compression.meta.json": [],
            "_operator.data.json": [],
            "sysconfig.meta.json": [],
            "operator.data.json": [],
            "types.data.json": [],
            "pluggy": {
                "_hooks.data.json": [],
                "_version.data.json": [],
                "_manager.data.json": [],
                "_tracing.data.json": [],
                "_result.meta.json": [],
                "_result.data.json": [],
                "_manager.meta.json": [],
                "_tracing.meta.json": [],
                "_version.meta.json": [],
                "_hooks.meta.json": [],
                "_warnings.meta.json": [],
                "_callers.meta.json": [],
                "__init__.meta.json": [],
                "__init__.data.json": [],
                "_callers.data.json": [],
                "_warnings.data.json": [],
            },
            "zipfile.data.json": [],
            "arcon": {
                "_version.data.json": [],
                "_version.meta.json": [],
                "__init__.meta.json": [],
                "__init__.data.json": [],
            },
            "bdb.data.json": [],
            "_socket.data.json": [],
            "stat.meta.json": [],
            "copyreg.data.json": [],
            "numbers.data.json": [],
            "re.meta.json": [],
            "csv.meta.json": [],
            "_socket.meta.json": [],
            "bdb.meta.json": [],
            "os": {
                "path.data.json": [],
                "path.meta.json": [],
                "__init__.meta.json": [],
                "__init__.data.json": [],
            },
            "copyreg.meta.json": [],
            "stat.data.json": [],
            "numbers.meta.json": [],
            "re.data.json": [],
            "csv.data.json": [],
            "_compression.data.json": [],
            "inspect.meta.json": [],
            "pickle.data.json": [],
            "operator.meta.json": [],
            "_operator.meta.json": [],
            "sysconfig.data.json": [],
            "zipfile.meta.json": [],
            "types.meta.json": [],
            "marshal.data.json": [],
            "_stat.data.json": [],
            "importlib": {
                "abc.meta.json": [],
                "machinery.data.json": [],
                "abc.data.json": [],
                "machinery.meta.json": [],
                "__init__.meta.json": [],
                "util.meta.json": [],
                "util.data.json": [],
                "__init__.data.json": [],
                "metadata": {
                    "__init__.meta.json": [],
                    "__init__.data.json": [],
                },
            },
            "_thread.meta.json": [],
            "fnmatch.data.json": [],
            "cmd.meta.json": [],
            "array.data.json": [],
            "signal.data.json": [],
            "filecmp.meta.json": [],
            "_weakref.meta.json": [],
            "sre_constants.data.json": [],
            "struct.data.json": [],
            "collections": {
                "abc.meta.json": [],
                "abc.data.json": [],
                "__init__.meta.json": [],
                "__init__.data.json": [],
            },
            "_csv.meta.json": [],
            "iniconfig": {
                "_parse.data.json": [],
                "_parse.meta.json": [],
                "__init__.meta.json": [],
                "exceptions.meta.json": [],
                "exceptions.data.json": [],
                "__init__.data.json": [],
            },
            "math.data.json": [],
            "__future__.data.json": [],
            "doctest.meta.json": [],
            "heapq.meta.json": [],
            "_random.data.json": [],
            "uuid.meta.json": [],
            "tempfile.data.json": [],
            "string.meta.json": [],
            "gzip.data.json": [],
            "reprlib.data.json": [],
            "weakref.meta.json": [],
            "asyncio": {
                "queues.meta.json": [],
                "events.meta.json": [],
                "transports.data.json": [],
                "subprocess.meta.json": [],
                "tasks.data.json": [],
                "protocols.meta.json": [],
                "selector_events.meta.json": [],
                "selector_events.data.json": [],
                "subprocess.data.json": [],
                "tasks.meta.json": [],
                "protocols.data.json": [],
                "events.data.json": [],
                "transports.meta.json": [],
                "queues.data.json": [],
                "futures.data.json": [],
                "streams.meta.json": [],
                "runners.data.json": [],
                "unix_events.meta.json": [],
                "locks.data.json": [],
                "__init__.meta.json": [],
                "coroutines.meta.json": [],
                "exceptions.meta.json": [],
                "base_events.data.json": [],
                "base_events.meta.json": [],
                "coroutines.data.json": [],
                "exceptions.data.json": [],
                "unix_events.data.json": [],
                "locks.meta.json": [],
                "__init__.data.json": [],
                "streams.data.json": [],
                "runners.meta.json": [],
                "futures.meta.json": [],
            },
            "unicodedata.meta.json": [],
            "_ast.data.json": [],
            "keyword.meta.json": [],
            "_collections_abc.data.json": [],
            "logging": {
                "handlers.data.json": [],
                "__init__.meta.json": [],
                "handlers.meta.json": [],
                "__init__.data.json": [],
            },
            "sre_parse.data.json": [],
            "msvcrt.data.json": [],
            "bz2.data.json": [],
            "email": {
                "header.meta.json": [],
                "charset.meta.json": [],
                "message.data.json": [],
                "message.meta.json": [],
                "charset.data.json": [],
                "header.data.json": [],
                "errors.data.json": [],
                "utils.meta.json": [],
                "__init__.meta.json": [],
                "policy.data.json": [],
                "contentmanager.data.json": [],
                "contentmanager.meta.json": [],
                "policy.meta.json": [],
                "utils.data.json": [],
                "__init__.data.json": [],
                "errors.meta.json": [],
            },
            "ast.meta.json": [],
            "tokenize.meta.json": [],
            "threading.meta.json": [],
            "bisect.meta.json": [],
            "copy.meta.json": [],
            "locale.meta.json": [],
            "functools.meta.json": [],
            "_pytest": {
                "_version.data.json": [],
                "scope.meta.json": [],
                "compat.meta.json": [],
                "logging.data.json": [],
                "python.data.json": [],
                "capture.data.json": [],
                "python_api.meta.json": [],
                "_argcomplete.data.json": [],
                "outcomes.data.json": [],
                "terminal.data.json": [],
                "timing.data.json": [],
                "main.data.json": [],
                "hookspec.meta.json": [],
                "deprecated.data.json": [],
                "recwarn.data.json": [],
                "nodes.meta.json": [],
                "tmpdir.data.json": [],
                "monkeypatch.data.json": [],
                "config": {
                    "compat.meta.json": [],
                    "argparsing.meta.json": [],
                    "argparsing.data.json": [],
                    "compat.data.json": [],
                    "findpaths.meta.json": [],
                    "__init__.meta.json": [],
                    "exceptions.meta.json": [],
                    "exceptions.data.json": [],
                    "__init__.data.json": [],
                    "findpaths.data.json": [],
                },
                "helpconfig.data.json": [],
                "monkeypatch.meta.json": [],
                "helpconfig.meta.json": [],
                "recwarn.meta.json": [],
                "nodes.data.json": [],
                "tmpdir.meta.json": [],
                "main.meta.json": [],
                "deprecated.meta.json": [],
                "hookspec.data.json": [],
                "terminal.meta.json": [],
                "timing.meta.json": [],
                "python_api.data.json": [],
                "_argcomplete.meta.json": [],
                "outcomes.meta.json": [],
                "mark": {
                    "structures.meta.json": [],
                    "structures.data.json": [],
                    "expression.meta.json": [],
                    "__init__.meta.json": [],
                    "expression.data.json": [],
                    "__init__.data.json": [],
                },
                "logging.meta.json": [],
                "python.meta.json": [],
                "capture.meta.json": [],
                "scope.data.json": [],
                "compat.data.json": [],
                "_code": {
                    "code.meta.json": [],
                    "code.data.json": [],
                    "source.meta.json": [],
                    "__init__.meta.json": [],
                    "__init__.data.json": [],
                    "source.data.json": [],
                },
                "assertion": {
                    "rewrite.meta.json": [],
                    "rewrite.data.json": [],
                    "truncate.data.json": [],
                    "__init__.meta.json": [],
                    "util.meta.json": [],
                    "util.data.json": [],
                    "__init__.data.json": [],
                    "truncate.meta.json": [],
                },
                "_version.meta.json": [],
                "warnings.meta.json": [],
                "pathlib.data.json": [],
                "freeze_support.data.json": [],
                "pytester_assertions.meta.json": [],
                "legacypath.data.json": [],
                "cacheprovider.data.json": [],
                "_io": {
                    "terminalwriter.meta.json": [],
                    "saferepr.meta.json": [],
                    "saferepr.data.json": [],
                    "terminalwriter.data.json": [],
                    "pprint.meta.json": [],
                    "wcwidth.meta.json": [],
                    "__init__.meta.json": [],
                    "wcwidth.data.json": [],
                    "__init__.data.json": [],
                    "pprint.data.json": [],
                },
                "reports.meta.json": [],
                "stash.meta.json": [],
                "doctest.data.json": [],
                "__init__.meta.json": [],
                "runner.data.json": [],
                "warning_types.data.json": [],
                "debugging.meta.json": [],
                "fixtures.data.json": [],
                "pytester.data.json": [],
                "fixtures.meta.json": [],
                "pytester.meta.json": [],
                "runner.meta.json": [],
                "warning_types.meta.json": [],
                "debugging.data.json": [],
                "cacheprovider.meta.json": [],
                "reports.data.json": [],
                "stash.data.json": [],
                "doctest.meta.json": [],
                "__init__.data.json": [],
                "pytester_assertions.data.json": [],
                "legacypath.meta.json": [],
                "freeze_support.meta.json": [],
                "pathlib.meta.json": [],
                "warnings.data.json": [],
            },
            "selectors.data.json": [],
            "pprint.data.json": [],
            "sre_compile.data.json": [],
            "io.meta.json": [],
            "tty.meta.json": [],
            "codecs.meta.json": [],
            "typing_extensions.data.json": [],
            "_warnings.data.json": [],
            "pathlib.meta.json": [],
            "warnings.data.json": [],
        },
    },
    ".gitignore": [
        "*build/",
        "*coverage*",
        "*venv",
        ".DS_Store",
        ".env",
        "__pycache__/",
        "dist/",
        "node_modules/",
    ],
    "package-lock.json": [],
    "package.json": [],
    "CONTRIBUTING.md": [],
    ".github": {
        "COMMIT_POLICY.md": [],
        "workflows": {"codeql-analysis.yml": [], "build.yaml": ""},
        "dependabot.yml": [],
    },
    "coverage.xml": [],
    "poetry.lock": [],
    "README.rst": [],
    ".git": {
        "HEAD": [],
    },
    ".idea": {
        "docsig.iml": [],
        "jsonSchemas.xml": [],
        "inspectionProfiles": {
            "profiles_settings.xml": [],
            "Project_Default.xml": [],
        },
        "codeStyles": {"Project.xml": [], "codeStyleConfig.xml": ""},
        "material_theme_project_new.xml": [],
        "vcs.xml": [],
        ".gitignore": [
            "/dataSources.local.xml",
            "/dataSources/",
            "/dictionaries",
            "/httpRequests/",
            "/shelf/",
            "/sonarlint/",
            "/tasks.xml",
            "/usage.statistics.xml",
            "/workspace.xml",
        ],
        "workspace.xml": [],
        "modules.xml": [],
        "watcherTasks.xml": [],
        "dictionaries": {"swhitlock.xml": [], "default_user.xml": ""},
        "misc.xml": [],
        "scopes": {
            "whitelist_py.xml": [],
            "bump2version.xml": [],
            "docs__themes_graphite_static.xml": [],
            "docs_conf.xml": [],
            "_prettierignore.xml": [],
            "docs_index.xml": [],
            "_pylintrc.xml": [],
        },
    },
}


def test_exclude_defaults(
    capsys: pytest.CaptureFixture,
    main: MockMainType,
    make_tree: FixtureMakeTree,
) -> None:
    """Test bash script is ignored when under __pycache__ directory.

    :param capsys: Capture sys out.
    :param main: Patch package entry point.
    :param make_tree: Create directory tree from dict mapping.
    """
    make_tree(Path.cwd(), TREE)
    main(".", long.verbose)
    std = capsys.readouterr()
    expected = [
        f"{Path('.pyaud_cache/7.5.1/.gitignore')}: Parsing Python code failed",
        f"{Path('.pytest_cache')}: in exclude list, skipping",
        f"{Path('dist')}: in exclude list, skipping",
        f"{Path('node_modules')}: in exclude list, skipping",
        f"{Path('tests/__pycache__')}: in exclude list, skipping",
        f"{Path('docsig/__pycache__')}: in exclude list, skipping",
        f"{Path('.mypy_cache')}: in exclude list, skipping",
        f"{Path('.gitignore')}: Parsing Python code failed",
        f"{Path('.git')}: in exclude list, skipping",
        f"{Path('.idea')}: in exclude list, skipping",
    ]
    assert all(i in std.out for i in expected)


def test_exclude_argument(
    init_file: InitFileFixtureType,
    main: MockMainType,
) -> None:
    """Test bash script is ignored when exclude argument passed.

    :param init_file: Initialize a test file.
    :param main: Mock ``main`` function.
    """
    template = """
#!/usr/bin/env bash
new-ssl() {
  domain="${1}"
  config="${2:-"${domain}.conf"}"
  openssl \
    req \
    -new \
    -newkey \
    rsa:2048 \
    -nodes \
    -sha256 \
    -out "${domain}.csr" \
    -keyout "${domain}.key" \
    -config "${config}"
}

new-ssl "${@}"
"""
    init_file(template)
    assert main(".", long.exclude, "file.py") == 0
