---
name: Build IntelliJ Plugin
on:
  push:
    branches:
      - master
    paths:
      - plugin/intellij/**
      - plugin/intellij
      - .github/workflows/build-intellij-plugin.yaml
  pull_request:
    branches:
      - master
    paths:
      - plugin/intellij/**
      - plugin/intellij
      - .github/workflows/build-intellij-plugin.yaml

concurrency:
  group: >-
    ${{ github.workflow }}-${{
      github.event.pull_request.number || github.ref
    }}
  cancel-in-progress: true

env:
  PLUGIN_DIR: plugin/intellij

jobs:
  build:
    name: intellij-plugin
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Maximize Build Space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          large-packages: false

      - name: Fetch Sources
        uses: actions/checkout@v6
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: jetbrains
          java-version: "21"

      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v6

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build Linted Plugin
        working-directory: ${{ env.PLUGIN_DIR }}
        run: make build

      - name: Verify Plugin
        working-directory: ${{ env.PLUGIN_DIR }}
        run: make verify

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: plugin-distribution
          path: ${{ env.PLUGIN_DIR }}/build/distributions/*.zip

      - name: Collect Tests Result
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: tests-result
          path: ${{ env.PLUGIN_DIR }}/build/reports/tests

      - name: Collect Plugin Verifier Result
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: plugin-verifier-result
          path: ${{ env.PLUGIN_DIR }}/build/reports/pluginVerifier
