name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  ci:
    name: >
      ${{ matrix.os }}
      -python${{ matrix.python-version }}
      -node@${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
    env:
      PYAUD_GH_NAME: jshwi
      PYAUD_GH_EMAIL: stephen@jshwisolutions.com
      PYAUD_GH_TOKEN: ${{ secrets.PYAUD_GH_TOKEN }}
    strategy:
      matrix:
        python-version: [3.8]
        node-version: [16.x.x]
        os: [ubuntu-latest]
    steps:
      - name: Checkout build
        id: checkout-build
        uses: actions/checkout@v3
      - name: Install Poetry
        id: install-poetry
        run: pipx install poetry
      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
      - name: Setup Node
        id: setup-node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install Python Packages
        id: install-python-packages
        run: poetry install
      - name: Install Node Packages
        id: install-node-packages
        run: npm install
      - name: Audit
        id: audit
        run: npm run audit
      - name: Upload coverage
        id: upload-coverage
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
