---
name: CodSpeed
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

env:
  PYTHONIOENCODING: utf-8
  UV: uv
  UV_PYTHON: "3.12"

jobs:
  benchmarks:
    name: benchmarks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Build
        id: checkout-build
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Get uv Version
        id: get-uv-version
        run: echo "version=$(cat .uv-version)" >> "$GITHUB_OUTPUT"
        shell: bash
      - name: Setup uv
        id: setup-uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          version: "${{ steps.get-uv-version.outputs.version }}"
          enable-cache: true
      - name: Install Dependencies
        id: install-dependencies
        run: make install-venv
      - name: Run Benchmarks
        id: run-benchmarks
        uses: CodSpeedHQ/action@88472375d0a4572cf70a9f1fe3a4e0ab8da1b924 # v5.0.1
        with:
          run: uv run --no-sync pytest tests/benchmark_test.py --codspeed
          token: "${{ secrets.CODSPEED_TOKEN }}"
